const de = {
  appTitle: "HUNGRY POLY",
  tagline: "Lerne Vokabeln beim Burger-Bauen",
  login: "Anmelden",
  register: "Registrieren",
  username: "Benutzer",
  password: "Passwort",
  displayName: "Anzeigename",
  loading: "Laden...",
  enter: "Anmelden",
  createAccount: "Konto erstellen",
  playAsGuest: "Als Gast spielen",
  vsAiModePickerTitle: "Wahle dein Spiel gegen die KI",
  vsAiModePickerDesc: "Du kannst ein normales Spiel starten oder zuerst mit dem Tutorial lernen.",
  vsAiModePickerNormalLabel: "Einfaches Spiel",
  vsAiModePickerNormalNeedHat: "Stelle deinen Modus ein und wahle deinen Hut, um spielen zu konnen.",
  vsAiModePickerNormalReady: "Tritt in diesem Modus gegen die KIs an.",
  vsAiModePickerTutorialLabel: "Tutorial",
  vsAiModePickerTutorialDesc: "Lerne hier die Grundlagen des Spiels.",
  yourName: "DEIN NAME",
  enterName: "Gib deinen Namen ein...",
  chooseLanguage: "WÄHLE DEINE SPRACHE",
  gameMode: "SPIELMODUS",
  modeClon: "Klon",
  modeEscalera: "Treppe",
  modeCaotico: "Chaotisch",
  modeClonDesc: "Alle gleich",
  modeEscaleraDesc: "Aufsteigend",
  modeCaoticoDesc: "Alles zufällig!",
  burgerCount: "BURGER",
  ingredientCount: "ZUTATEN PRO BURGER",
  cloneIngredientPool: "ZUTATEN-POOL",
  cloneIngredientPoolHint: "Wähle, welche Zutaten in Burgern des Klon-Modus erscheinen können.",
  cloneIngredientPoolLocked: "Brot ist immer enthalten.",
  cloneRemovedActions: "ENTFERNTE AKTIONSKARTEN",
  cloneRemovedActionsNone: "Diese Auswahl entfernt keine Aktionskarten.",
  cloneWildcardsToggle: "JOKER IM DECK",
  cloneWildcardsOn: "Joker aktiviert",
  cloneWildcardsOff: "Joker deaktiviert",
  ingredientsLabelShort: "ZUTATEN",
  cloneRemovedActionsLabel: "Entfernte Aktionskarten",
  cloneNoRemovedActions: "Es wird keine Aktionskarte entfernt",
  perPlayerLabel: "PRO SPIELER",
  aiOpponents: "KI-GEGNER",
  addAiPlayer: "KI hinzufügen",
  removeAiPlayer: "KI entfernen",
  aiDifficulty: "KI-SCHWIERIGKEIT",
  aiEasy: "Leicht",
  aiMedium: "Mittel",
  aiHard: "Schwer",
  aiImpossible: "Unmöglich",
  opponent1: "1 Gegner",
  opponents3: "3 Gegner",
  vsAI: "🎮 vs KI",
  online: "🌐 Online",
  history: "Verlauf",
  logout: "Abmelden",
  back: "← Zurück",
  gameHistory: "Spielverlauf",
  games: "SPIELE",
  wins: "SIEGE",
  losses: "NIEDERLAGEN",
  winrate: "WINRATE",
  all: "Alle",
  winsFilter: "Siege",
  lossesFilter: "Niederlagen",
  noGames: "Keine Spiele aufgezeichnet",
  victory: "Sieg",
  defeatBy: (name) => `Niederlage — ${name} hat gewonnen`,
  multiplayerOnline: "Online Mehrspieler",
  playWithFriends: "Spiele mit Freunden in Echtzeit",
  createRoom: "➕ Raum erstellen",
  lobby: "🏠 Lobby",
  code: "🔑 Code",
  roomType: "RAUMTYP",
  private: "🔒 Privat",
  codeOnly: "Nur mit Code",
  public: "🌐 Öffentlich",
  visibleInLobby: "Im Lobby sichtbar",
  roomName: "RAUMNAME",
  roomNamePlaceholder: "Z.B.: Schnelles Spiel",
  creating: "⏳ Erstellen...",
  createRoomBtn: "🎮 Raum erstellen",
  publicRooms: "ÖFFENTLICHE RÄUME",
  loadingRooms: "⏳ Räume laden...",
  noPublicRooms: "Es gibt keine aktiven Räume",
  filterByMode: "Nach Modus filtern",
  noPublicRoomsForMode: "Keine öffentlichen Räume für diesen Modus",
  createYourRoom: "Erstelle deinen Raum",
  players: "Spieler",
  join: "Beitreten",
  roomCode: "RAUMCODE",
  roomCodePlaceholder: "Z.B.: ABCD1",
  joining: "⏳ Beitreten...",
  joinBtn: "🔗 Beitreten",
  timeout: "Zeitüberschreitung. Bitte erneut versuchen.",
  enterNameFirst: "Gib zuerst deinen Namen ein",
  backToMenu: "← Zurück zum Menü",
  publicRoom: "🌐 ÖFFENTLICHER RAUM",
  privateRoom: "🔒 RAUMCODE",
  codeLabel: "Code",
  shareCode: "Teile diesen Code oder Link mit deinen Freunden",
  linkCopied: "✅ Link kopiert!",
  inviteLink: "🔗 Mit Link einladen",
  playersCount: (n) => `SPIELER (${n}/6)`,
  you: "(du)",
  host: "👑 Host",
  waitingPlayers: "⏳ Warte auf mehr Spieler...",
  yourLanguage: "DEINE SPRACHE",
  chooseOne: "(wähle eine)",
  waitingHats: (n, total) => `⏳ Warte auf Hüte (${n}/${total})`,
  startGame: "🚀 Spiel starten!",
  chooseHat: "👆 Wähle deinen Sprach-Hut",
  waitingHost: "⏳ Warte auf den Host...",
  leaveRoom: "← Raum verlassen",
  extraPlayMsg: "Du kannst eine Zutat spielen!",
  yourTurn: "Dein Zug",
  turnOfPlayer: (name) => `${name} ist dran`,
  tapContinue: "Tippe zum Fortfahren...",
  playerWon: (name) => `${name} hat gewonnen!`,
  wonByAbandon: "Sieg durch Aufgabe!",
  abandonSubtitle: (name) => `${name} hat das Spiel verlassen.`,
  youLost: "Du hast verloren!",
  completedBurgers: "Hat alle Burger zuerst fertiggestellt",
  playAgain: "🔄 Nochmal spielen",
  historyBtn: "📊 Verlauf",
  yourTurnLabel: "🎴 Dein Zug",
  turnActionsLabel: "Was kann ich tun?",
  actionName_milanesa: "Die Milanesa",
  actionDesc_milanesa: "Alle werfen Brot und Ei ab",
  actionName_ensalada: "Der Salat",
  actionDesc_ensalada: "Alle werfen Obst/Gemüse ab",
  actionName_pizza: "Die Pizza",
  actionDesc_pizza: "Alle werfen Käse ab",
  actionName_parrilla: "Der Grill",
  actionDesc_parrilla: "Alle werfen Huhn und Fleisch ab",
  actionName_tenedor: "Die Gabel",
  actionDesc_tenedor: "Stiehl eine Zutat von einem Spieler",
  actionName_ladron: "Hutdieb",
  actionDesc_ladron: "Stiehlt einen Haupthut",
  actionName_intercambio_sombreros: "Huttausch",
  actionDesc_intercambio_sombreros: "Tauscht Hüte",
  actionName_intercambio_hamburguesa: "Tischtausch",
  actionDesc_intercambio_hamburguesa: "Tauscht Tisch-Zutaten",
  actionName_perchero_cubierto: "Verdeckte Garderobe",
  actionDesc_perchero_cubierto: "Blockiert Wechseln/Hinzufügen und Hutkarten für einen Zug",
  actionName_basurero: "Der Mülleimer",
  actionDesc_basurero: "Hole aus dem Ablagestapel",
  actionName_gloton: "Der Vielfraß",
  actionDesc_gloton: "Leert den Tisch eines Spielers",
  actionName_negacion: "Negation",
  actionDesc_negacion: "Blockiert eine gegnerische Aktion",
  actionName_comecomodines: "Jokerfresser",
  actionDesc_comecomodines: "Alle werfen ihre Joker vom Tisch ab",
  actionNoObjectives: "Keine Ziele für diese Karte gefunden",
  closetCoverPrompt: (name) => name + ' hat deine Garderobe verdeckt. Willst du 2 Karten abwerfen, um den Effekt zu vermeiden?',
  closetCoverChooseTwo: "Wähle 2 Karten aus deiner Hand, um diese Karte zu vermeiden.",
  closetCoverDiscardTwo: "2 abwerfen und vermeiden",
  closetCoverAccept: "Effekt annehmen",
  closetCoveredStatus: "Garderobe verdeckt",
  howToPlayDesc: "Schnelle Zughilfe: Nutze Zutatenkarten, um deinen Burger zu vervollständigen, und Aktionskarten, um das Spiel zu beeinflussen.",
  howToPlayPage: "Seite",
  howToPlayTurnRulesTitle: "Zugregeln",
  howToPlayModeIntro: "Jedes Spiel nutzt einen anderen Modus. Hier kannst du sehen, welcher gerade aktiv ist und was sich am Ziel ändert.",
  currentModeBadge: "Aktuell",
  modeClonDetailed: "Alle Spieler erhalten genau dieselben Ziel-Burger. Die Schwierigkeit liegt darin, sie vor den anderen fertigzustellen, nicht in unterschiedlichen Aufträgen.",
  modeEscaleraDetailed: "Deine Burger wachsen von klein nach groß. Du beginnst mit einfacheren Zielen und jeder nächste Burger verlangt mehr Zutaten.",
  modeCaoticoDetailed: "Die Anzahl der Burger und die benötigten Zutaten ändern sich unvorhersehbarer. Das ist der variabelste Modus und kann kurze oder sehr anspruchsvolle Partien erzeugen.",
  howToPlayRuleOneCard: "Pro Zug darfst du nur eine Karte spielen: Zutat oder Aktion.",
  howToPlayRuleHatButtonsBeforePlay: "Die Buttons Wechseln und Hinzufügen dürfen nur vor dem Ausspielen einer Karte benutzt werden.",
  howToPlayRuleHatButtonsIngredientOnly: "Wenn du Wechseln oder Hinzufügen nutzt, darfst du danach nur eine Zutatenkarte spielen.",
  howToPlayIngredientTitle: "Zutatenkarte",
  howToPlayIngredientDesc: "Die Zutatenkarte muss zu deinem Haupthut passen und eine Zutat sein, die dein Burger noch braucht.",
  howToPlayActionTitle: "Aktionskarte",
  howToPlayActionDesc: "Aktionskarten erlauben dir je nach Symbol zu stehlen, zu tauschen oder zu blockieren.",
  howToPlayActionSingleTitle: "Ein-Person-Symbol",
  howToPlayActionSingleDesc: "Diese Aktion betrifft einen Spieler.",
  howToPlayActionGlobalTitle: "Mehrere-Personen-Symbol",
  howToPlayActionGlobalDesc: "Diese Aktion betrifft alle anderen Spieler.",
  howToPlayActionDiscardTitle: "Karten-Symbol",
  howToPlayActionDiscardDesc: "Mit dieser Aktion holst du eine Zutat aus dem Ablagestapel.",
  howToPlayActionNegationTitle: "X-Symbol",
  howToPlayActionNegationDesc: "Das ist die Negationskarte.",
  howToPlayOthersDiscardLabel: "Die anderen werfen ab:",
  howToPlayEffectLabel: "Effekt:",
  howToPlayEffectTenedor: "Du stiehlst 1 Zutat vom Tisch eines Spielers.",
  howToPlayEffectLadron: "Du stiehlst den Haupthut eines Spielers.",
  howToPlayEffectIntercambioSombreros: "Du tauschst Hüte mit einem Spieler.",
  howToPlayEffectIntercambioMesa: "Du tauschst deinen Zutatentisch mit dem eines Spielers.",
  howToPlayEffectGloton: "Du leerst den Zutatentisch eines Spielers.",
  howToPlayGoalTitle: "Spielziel",
  howToPlayEffectPercheroCubierto: "Blockiert den Garderobenständer eines anderen Spielers in seinem nächsten Zug, außer er wirft beim Erhalt 2 Karten ab.",
  howToPlayGoalDesc: "Wer zuerst alle Ziel-Burger fertigstellt, gewinnt.",
  howToPlayMainHatsTitle: "Haupthüte",
  howToPlayMainHatsDesc: "Deine Haupthüte bestimmen, welche Zutatenkarten du in deinem Zug spielen kannst.",
  howToPlayHatButtonsTitle: "Haupthut-Buttons",
  howToPlayChangeHatRule: "Wechseln: vor dem Spielen nutzen; danach darfst du nur 1 Zutat spielen.",
  howToPlayAddHatRule: "Hinzufügen: vor dem Spielen nutzen; danach darfst du nur 1 Zutat spielen.",
  howToPlayClosetTitle: "Hutständer",
  howToPlayClosetDesc: (n) => `Hier lagerst du zusätzliche Hüte zum Wechseln oder Hinzufügen. Aktuell hast du ${n}.`,
  prevPage: "Zurück",
  nextPage: "Weiter",
  howToPlayActionPageSingle: "Aktionen: ein Spieler",
  howToPlayActionPageGlobal: "Aktionen: alle anderen Spieler",
  howToPlayActionPageNegDiscard: "Aktionen: Negation und Ablage",
  tiPlayIngDesc: "Spiele eine Zutatenkarte, die zu deinem Haupthut passt und die dein Burger braucht.",
  tiPlayCardDesc: "Spiele eine Aktionskarte (⚡), um Gegner zu beeinflussen. Sie können sie mit Negation 🚫 blockieren!",
  tiDiscardDesc: "Wirf eine beliebige Karte ab, um deinen Zug zu beenden. Deine Hand wird automatisch aufgefüllt.",
  extraPlayLabel: "🍔 Du kannst eine Zutat hinzufügen",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Raum",
  log: "📋 Log",
  chat: "💬 Chat",
  leave: "🚪 Verlassen",
  opponents: "GEGNER",
  historyLog: "VERLAUF",
  noEvents: "Noch keine Ereignisse",
  burgers: "BURGER",
  table: "TISCH",
  tableCount: (n) => `TISCH (${n} Zutaten)`,
  emptyTable: "Leerer Tisch",
  sharedGoalsLabel: "Gemeinsame Ziele",
  mainHat: "HAUPT",
  closet: "GARDEROBE",
  viewCloset: (n) => `🧥 Garderobe (${n})`,
  changeHat: "🎩 Wechseln",
  changeHatTooltip: "Wechsle deinen Haupthut (kostet die Hälfte deiner Hand)",
  addHat: "➕ Hinzufügen",
  addHatTooltip: "Füge einen Hut hinzu (wirf ganze Hand ab, Max wird reduziert)",
  hand: "HAND",
  maxReduced: "Max reduziert durch Hinzufügen",
  canPlay: "✅ Spielbar",
  cantPlay: "❌ Nicht spielbar",
  cantPlayNow: "❌ Diese Karte kann jetzt nicht gespielt werden",
  canPlayThis: "✅ Du kannst diese Karte spielen",
  play: "▶ Spielen",
  discard: "🗑 Abwerfen",
  skipTurn: "⏭ Zug passen",
  waitingOnline: (name) => `🌐 Warte auf ${name}s Zug...`,
  waitingLocal: (name) => `⏳ Warte auf ${name}...`,
  cardsInHand: (n) => `🃏 ${n} Karten auf der Hand`,
  turn: "⟵ Zug",
  wildcardChoose: "Wähle die Zutat die du brauchst",
  ingredientCard: "🃏 Zutatenkarte",
  ingredientTag: "Zutat",
  actionCard: "⚡ Aktionskarte",
  tableTab: "🍔 Tisch",
  rivalsTab: "👥 Gegner",
  chatTab: "💬 Chat",
  chooseOpponent: "Wähle Gegner",
  tableLabel: "Tisch",
  empty: "leer",
  burgersLabel: "Burger",
  cancel: "Abbrechen",
  forkSteal: "🍴 Die Gabel — Wähle Zutat zum Stehlen",
  chooseNewHat: "🎩 Wähle neuen Haupthut",
  waitingHatChoice: (name) => `⏳ Warte auf ${name}s Hut-Wahl...`,
  hatStolen: "Dein Haupthut wurde gestohlen. Wähle einen aus der Garderobe.",
  hatExchange: "🔄 Huttausch",
  hatExchangeDesc: (name) => `Wähle den Hut zum Geben und den zum Empfangen von ${name}.`,
  yourHatToGive: "Dein Hut zum Geben:",
  hatToReceive: (name) => `Hut den du von ${name} willst:`,
  exchange: "Tauschen",
  close: "Schließen",
  changeHatStep1: "🎩 Hut wechseln — Schritt 1: Hut wählen",
  changeHatStep1Desc: (n) => `Wähle einen Hut aus der Garderobe. Dann wählst du ${n} Karte${n !== 1 ? 'n' : ''} zum Abwerfen.`,
  changeHatStep2: (lang) => `🎩 Wechsel zu ${lang} — Schritt 2: Karten wählen`,
  moreCards: (n) => `${n} Karte${n !== 1 ? 'n' : ''} mehr`,
  ready: "Fertig!",
  goBack: "← Zurück",
  confirmDiscard: "Abwurf bestätigen",
  addHatModal: "➕ Hut hinzufügen — wirf deine ganze Hand ab",
  addHatDesc: (max) => `Wähle einen Hut aus der Garderobe. Du wirfst deine ganze Hand ab und dein Karten-Max wird um 1 reduziert (auf ${max}).`,
  trashBin: "🗑️ Der Mülleimer — Wähle eine Karte vom Abwurfstapel",
  trashBinDesc: "Rette eine Zutat vom Abwurfstapel.",
  wildcard: "🌭 Joker — Wähle Zutat",
  wildcardNeeded: "Diese Zutaten fehlen dir noch:",
  wildcardAny: "Wähle die Zutat die der Joker darstellt:",
  wildcardActingAs: (name) => `Joker als: ${name}`,
  wildcardCanBe: "Kann jede Zutat darstellen",
  names: "Namen",
  affectingCards: "Karten die es beeinflussen",
  negation: "🚫 Negation?",
  negationPlayed: (player, card) => `<strong>${player}</strong> hat <strong>${card}</strong> gespielt`,
  negationQuestion: "Willst du eine Negationskarte benutzen um diese Aktion zu blockieren?",
  deny: "🚫 Negieren",
  allow: "✅ Durchlassen",
  noMessages: "Noch keine Nachrichten",
  typeMessage: "Nachricht schreiben...",
  send: "Senden",
  reconnecting: "Verbinde zum Raum...",
  leftRoom: "Du hast den Raum verlassen",
  roomLabel: "Raum",
  wantToReturn: "Möchtest du zurück zum Raum?",
  returnToRoom: "Zurück zum Raum",
  noGoLobby: "Nein, zum Lobby",
  gamePaused: "Spiel pausiert",
  aloneTitle: "Du bist allein im Raum",
  aloneDesc: "Alle anderen Spieler sind gegangen",
  backToLobby: "Zurück zum Lobby",
  espanol: "Spanisch",
  ingles: "Englisch",
  frances: "Französisch",
  italiano: "Italienisch",
  aleman: "Deutsch",
  portugues: "Portugiesisch",
  langLabel: "Sprache",
  friends: "Freunde",
  friendsList: "Freundesliste",
  friendRequests: "Anfragen",
  addFriend: "Freund hinzufügen",
  searchUsers: "Benutzer suchen...",
  sendRequest: "Anfrage senden",
  requestSent: "Anfrage gesendet",
  noFriends: "Noch keine Freunde",
  onlineStatus: "Online",
  offlineStatus: "Offline",
  accept: "Annehmen",
  decline: "Ablehnen",
  removeFriend: "Entfernen",
  inviteFriend: "Freund einladen",
  inviteSent: "Einladung gesendet",
  roomInvite: "hat dich in einen Raum eingeladen",
  joinRoom: "Beitreten",
  noRequests: "Keine ausstehenden Anfragen",
  noResults: "Keine Ergebnisse",
  alreadyFriends: "Bereits befreundet",
  requestAlreadySent: "Anfrage bereits gesendet",
  autoAccepted: "Automatisch akzeptiert",
  blockUser: "Blockieren",
  unblockUser: "Entsperren",
  blockedUsers: "Blockiert",
  noBlocked: "Keine blockierten Benutzer",
  inviteToRoom: "In Raum einladen",
  friendAccepted: "hat deine Anfrage akzeptiert",
  friendRemovedNotif: "ist nicht mehr dein Freund",
  friendRequestNotif: "hat dir eine Freundschaftsanfrage geschickt",
  viewRequest: "Ansehen",
  addFriendShort: "Hinzufügen",
  profileMenu: "Profil",
  leaveLocal: "Partie verlassen",
  leaveLocalConfirm: "Das KI-Spiel verlassen und zum Setup zuruckkehren?",
  homeMenu: "Start",
  gameLanguageMenu: "Spielsprache"
};

export default de;
