const es = {
  appTitle: "HUNGRY POLY",
  tagline: "Aprende vocabulario armando hamburguesas",
  login: "Iniciar Sesión",
  register: "Registrarse",
  username: "Usuario",
  password: "Contraseña",
  displayName: "Nombre para mostrar",
  loading: "Cargando...",
  enter: "Entrar",
  createAccount: "Crear cuenta",
  playAsGuest: "Jugar como invitado",
  vsAiModePickerTitle: "Elige tu partida vs IA",
  vsAiModePickerDesc: "Puedes empezar una partida normal o aprender primero con el tutorial.",
  vsAiModePickerNormalLabel: "Partida simple",
  vsAiModePickerNormalNeedHat: "Configura tu modo y elige tu sombrero para poder jugar.",
  vsAiModePickerNormalReady: "Enfrentate a las IAs en este modo.",
  vsAiModePickerTutorialLabel: "Tutorial",
  vsAiModePickerTutorialDesc: "Aprende las bases del juego aqui.",
  yourName: "TU NOMBRE",
  enterName: "Ingresa tu nombre...",
  chooseLanguage: "ELIGE TU IDIOMA",
  gameMode: "MODO DE JUEGO",
  modeClon: "Clon",
  modeEscalera: "Escalera",
  modeCaotico: "Caótico",
  modeClonDesc: "Todas iguales",
  modeEscaleraDesc: "Ascendente",
  modeCaoticoDesc: "¡Todo aleatorio!",
  burgerCount: "HAMBURGUESAS",
  ingredientCount: "INGREDIENTES POR HAMBURGUESA",
  cloneIngredientPool: "PISCINA DE INGREDIENTES",
  cloneIngredientPoolHint: "Elige qué ingredientes pueden salir en las hamburguesas del modo Clon.",
  cloneIngredientPoolLocked: "Pan siempre está incluido.",
  cloneRemovedActions: "CARTAS DE ACCIÓN QUE SE QUITAN",
  cloneRemovedActionsNone: "Con esta selección no se quita ninguna carta de acción.",
  ingredientsLabelShort: "INGREDIENTES",
  perPlayerLabel: "POR JUGADOR",
  aiOpponents: "OPONENTES IA",
  cloneWildcardsToggle: "COMODINES EN EL MAZO",
  cloneWildcardsOn: "Comodines activados",
  cloneWildcardsOff: "Comodines desactivados",
  addAiPlayer: "Agregar IA",
  cloneRemovedActionsLabel: "Cartas de acción que se quitan",
  cloneNoRemovedActions: "No se quita ninguna carta de acción",
  removeAiPlayer: "Quitar IA",
  aiDifficulty: "DIFICULTAD IA",
  aiEasy: "Fácil",
  aiMedium: "Medio",
  aiHard: "Difícil",
  aiImpossible: "Imposible",
  opponent1: "1 oponente",
  opponents3: "3 oponentes",
  vsAI: "vs IA",
  online: "Online",
  history: "Historial",
  logout: "Salir",
  back: "← Volver",
  gameHistory: "Historial de Partidas",
  games: "PARTIDAS",
  wins: "VICTORIAS",
  losses: "DERROTAS",
  winrate: "WINRATE",
  all: "Todas",
  winsFilter: "Victorias",
  lossesFilter: "Derrotas",
  noGames: "Sin partidas registradas",
  victory: "Victoria",
  defeatBy: (name) => `Derrota — Ganó ${name}`,
  multiplayerOnline: "Multijugador Online",
  playWithFriends: "Juega con amigos en tiempo real",
  createRoom: "➕ Crear sala",
  lobby: "Lobby",
  code: "Código",
  roomType: "TIPO DE SALA",
  private: "Privada",
  codeOnly: "Solo con código",
  public: "Pública",
  visibleInLobby: "Visible en lobby",
  roomName: "NOMBRE DE SALA",
  roomNamePlaceholder: "Ej: Partida rápida",
  creating: "⏳ Creando...",
  createRoomBtn: "Crear sala",
  publicRooms: "SALAS PÚBLICAS",
  loadingRooms: "⏳ Cargando salas...",
  noPublicRooms: "No hay salas activas",
  filterByMode: "Filtrar por modo",
  noPublicRoomsForMode: "No hay salas públicas para ese modo",
  createYourRoom: "Crea tu sala",
  players: "jugadores",
  join: "Unirse",
  roomCode: "CÓDIGO DE SALA",
  roomCodePlaceholder: "Ej: ABCD1",
  joining: "⏳ Uniéndose...",
  joinBtn: " Unirse",
  timeout: "Tiempo de espera agotado. Intenta de nuevo.",
  enterNameFirst: "Ingresa tu nombre primero",
  backToMenu: "← Volver al menú",
  publicRoom: "SALA PÚBLICA",
  privateRoom: "CÓDIGO DE SALA",
  codeLabel: "Código",
  shareCode: "Comparte este código o enlace con tus amigos",
  linkCopied: "✅ ¡Enlace copiado!",
  inviteLink: "🔗 Invitar con enlace",
  playersCount: (n) => `JUGADORES (${n}/6)`,
  you: "(tú)",
  host: "👑 Host",
  waitingPlayers: "⏳ Esperando más jugadores...",
  yourLanguage: "TU IDIOMA",
  chooseOne: "(elige uno)",
  waitingHats: (n, total) => `⏳ Esperando sombreros (${n}/${total})`,
  startGame: "¡Iniciar partida!",
  chooseHat: "👆 Elige tu sombrero de idioma",
  waitingHost: "⏳ Esperando que el host inicie...",
  leaveRoom: "← Salir de la sala",
  extraPlayMsg: "¡Puedes jugar un ingrediente!",
  yourTurn: "Tu turno",
  tapContinue: "Toca para continuar...",
  playerWon: (name) => `¡${name} ganó!`,
  wonByAbandon: "¡Ganaste por abandono!",
  abandonSubtitle: (name) => `${name} abandonó la partida.`,
  youLost: "Perdiste",
  completedBurgers: "Completó todas sus hamburguesas primero",
  playAgain: "Jugar de nuevo",
  historyBtn: "Historial",
  yourTurnLabel: "Tu turno",
  turnActionsLabel: "Cómo jugar",
  actionName_milanesa: "La Milanesa",
  actionDesc_milanesa: "Todos descartan pan y huevo",
  actionName_ensalada: "La Ensalada",
  actionDesc_ensalada: "Todos descartan frutas/verduras",
  actionName_pizza: "La Pizza",
  actionDesc_pizza: "Todos descartan queso",
  actionName_parrilla: "La Parrilla",
  actionDesc_parrilla: "Todos descartan pollo y carne",
  actionName_tenedor: "El Tenedor",
  actionDesc_tenedor: "Roba ingrediente de otro",
  actionName_ladron: "Ladrón Sombreros",
  actionDesc_ladron: "Quita sombrero principal",
  actionName_intercambio_sombreros: "Intercambio Sombreros",
  actionDesc_intercambio_sombreros: "Intercambia sombreros",
  actionName_intercambio_hamburguesa: "Intercambio Mesa",
  actionDesc_intercambio_hamburguesa: "Intercambia ingredientes de mesa",
  actionName_perchero_cubierto: "Perchero Cubierto",
  actionDesc_perchero_cubierto: "Bloquea cambiar/agregar y cartas de sombrero por un turno",
  actionName_basurero: "El Basurero",
  actionDesc_basurero: "Busca en descartes",
  actionName_gloton: "El Glotón",
  actionDesc_gloton: "Vacía mesa de otro",
  actionName_negacion: "Negación",
  actionDesc_negacion: "Bloquea acción enemiga",
  actionName_comecomodines: "Come Comodines",
  actionDesc_comecomodines: "Todos descartan sus comodines de la mesa",
  actionNoObjectives: "No se pillaron objetivos para esta carta",
  closetCoverPrompt: (name) => name + ' te cubrió el perchero. ¿Quieres descartar 2 cartas para evitar el efecto?',
  closetCoverChooseTwo: "Elige 2 cartas de tu mano para evitar esta carta.",
  closetCoverDiscardTwo: "Descartar 2 y evitar",
  closetCoverAccept: "Aceptar efecto",
  closetCoveredStatus: "Perchero cubierto",
  howToPlayDesc: "Guía rápida del turno: usa cartas de ingredientes para completar tu hamburguesa y cartas de acción para afectar la partida.",
  howToPlayPage: "Página",
  howToPlayTurnRulesTitle: "Reglas del turno",
  howToPlayModeIntro: "Cada partida usa un modo distinto. Aquí puedes ver cuál está activo ahora y qué cambia en el objetivo.",
  currentModeBadge: "Actual",
  modeClonDetailed: "Todos los jugadores reciben exactamente las mismas hamburguesas objetivo. La dificultad viene de competir por completarlas antes que los demás, no de tener pedidos distintos.",
  modeEscaleraDetailed: "Tus hamburguesas crecen de menor a mayor. Empiezas con objetivos simples y cada hamburguesa siguiente pide más ingredientes, así que la partida escala poco a poco.",
  modeCaoticoDetailed: "La cantidad de hamburguesas y los ingredientes necesarios cambian de forma más impredecible. Es el modo más variable y puede generar partidas cortas o muy exigentes.",
  howToPlayRuleOneCard: "Por turno solo puedes jugar una carta: de ingrediente o de acción.",
  howToPlayRuleHatButtonsBeforePlay: "Los botones Cambiar y Agregar solo se pueden usar antes de haber jugado una carta.",
  howToPlayRuleHatButtonsIngredientOnly: "Si usas Cambiar o Agregar, luego solo puedes jugar una carta de ingrediente.",
  howToPlayIngredientTitle: "Carta de Ingrediente",
  howToPlayIngredientDesc: "La carta de ingrediente debe coincidir con tu sombrero principal y ser un ingrediente que tu hamburguesa todavía necesite.",
  howToPlayActionTitle: "Carta de Acción",
  howToPlayActionDesc: "Las cartas de acción te permiten robar, intercambiar o bloquear jugadas según el ícono de cada carta.",
  howToPlayActionSingleTitle: "Ícono de una persona",
  howToPlayActionSingleDesc: "Esta acción afecta a un solo jugador.",
  howToPlayActionGlobalTitle: "Ícono de varias personas",
  howToPlayActionGlobalDesc: "Esta acción afecta a todos los demás jugadores.",
  howToPlayActionDiscardTitle: "Ícono de cartas",
  howToPlayActionDiscardDesc: "Esta acción sirve para sacar un ingrediente del descarte.",
  howToPlayActionNegationTitle: "Ícono X",
  howToPlayActionNegationDesc: "Esta es la carta de Negación.",
  howToPlayOthersDiscardLabel: "Descartan los demás:",
  howToPlayEffectLabel: "Efecto:",
  howToPlayEffectTenedor: "Robas 1 ingrediente de la mesa de un jugador.",
  howToPlayEffectLadron: "Robas el sombrero principal de un jugador.",
  howToPlayEffectIntercambioSombreros: "Intercambias sombreros con un jugador.",
  howToPlayEffectIntercambioMesa: "Intercambias tu mesa de ingredientes con la de un jugador.",
  howToPlayEffectGloton: "Vacías la mesa de ingredientes de un jugador.",
  howToPlayGoalTitle: "Objetivo del juego",
  howToPlayEffectPercheroCubierto: "Bloquea el perchero de otro jugador durante su siguiente turno, salvo que descarte 2 cartas al recibirlo.",
  howToPlayGoalDesc: "Gana quien completa primero todas sus hamburguesas objetivo.",
  howToPlayMainHatsTitle: "Sombreros principales",
  howToPlayMainHatsDesc: "Tus sombreros principales determinan qué cartas de ingrediente puedes jugar en tu turno.",
  howToPlayHatButtonsTitle: "Botones del sombrero principal",
  howToPlayChangeHatRule: "Cambiar: úsalo antes de jugar carta; después solo podrás jugar 1 ingrediente.",
  howToPlayAddHatRule: "Agregar: úsalo antes de jugar carta; después solo podrás jugar 1 ingrediente.",
  howToPlayClosetTitle: "Perchero",
  howToPlayClosetDesc: (n) => `Aquí guardas sombreros extra para cambiar o agregar. Actualmente tienes ${n}.`,
  tiPlayIngDesc: "Jugá una carta de ingrediente que coincida con tu sombrero principal y que tu hamburguesa necesite.",
  tiPlayCardDesc: "Jugá una carta de acción (⚡) para afectar a los oponentes. ¡Pueden bloquearla con Negación 🚫!",
  tiDiscardDesc: "Descartá cualquier carta de tu mano para terminar tu turno. Tu mano se rellena automáticamente.",
  extraPlayLabel: "Puedes agregar un ingrediente",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Sala",
  log: " Log",
  chat: "💬 Chat",
  leave: "Salir",
  opponents: "OPONENTES",
  historyLog: "HISTORIAL",
  noEvents: "Sin eventos aún",
  burgers: "HAMBURGUESAS",
  table: "MESA",
  tableCount: (n) => `MESA (${n} ingredientes)`,
  emptyTable: "Mesa vacía",
  sharedGoalsLabel: "Objetivos compartidos",
  mainHat: "PRINCIPAL",
  closet: "PERCHERO",
  viewCloset: (n) => `🧥 Ver perchero (${n})`,
  changeHat: "🎩 Cambiar",
  changeHatTooltip: "Cambia tu sombrero principal (cuesta descartar la mitad de tu mano)",
  addHat: "➕ Agregar",
  addHatTooltip: "Agrega un sombrero extra (descarta toda tu mano, mano máx se reduce)",
  hand: "MANO",
  maxReduced: "Máx reducido por agregar",
  canPlay: "✅ Puedes jugar",
  cantPlay: "❌ No puedes jugar",
  cantPlayNow: "❌ No puedes jugar esta carta ahora (sombrero o ingrediente no necesario)",
  canPlayThis: "✅ Puedes jugar esta carta",
  play: "▶ Jugar",
  discard: "🗑 Descartar",
  skipTurn: "⏭ Pasar turno",
  waitingOnline: (name) => `🌐 Esperando la jugada de ${name}...`,
  waitingLocal: (name) => `⏳ Esperando a ${name}...`,
  cardsInHand: (n) => ` ${n} cartas en mano`,
  turn: "⟵ turno",
  wildcardChoose: "Escoge el ingrediente que necesites",
  ingredientCard: " Carta de Ingrediente",
  ingredientTag: "Ingrediente",
  actionCard: "⚡ Carta de Acción",
  tableTab: "🍔 Mesa",
  rivalsTab: "👥 Rivales",
  chatTab: "💬 Chat",
  chooseOpponent: "Elige oponente",
  tableLabel: "Mesa",
  empty: "vacía",
  burgersLabel: "Hambres",
  cancel: "Cancelar",
  forkSteal: "🍴 El Tenedor — Elige ingrediente a robar",
  chooseNewHat: "🎩 Elige nuevo sombrero principal",
  waitingHatChoice: (name) => `⏳ Esperando que ${name} elija su sombrero...`,
  hatStolen: "Tu sombrero principal fue robado. Elige uno del perchero.",
  hatExchange: "🔄 Intercambio de Sombreros",
  hatExchangeDesc: (name) => `Elige el sombrero que quieres dar y el que quieres recibir de ${name}.`,
  yourHatToGive: "Tu sombrero a dar:",
  hatToReceive: (name) => `Sombrero que quieres de ${name}:`,
  exchange: "Intercambiar",
  close: "Cerrar",
  changeHatStep1: "🎩 Cambiar Sombrero — paso 1: elegir sombrero",
  changeHatStep1Desc: (n) => `Elige un sombrero del perchero. Luego elegirás qué ${n} carta${n !== 1 ? 's' : ''} descartar. ¡Solo podrás jugar una carta de ingrediente después!`,
  changeHatStep2: (lang) => `🎩 Cambiar a ${lang} — paso 2: elegir cartas`,
  moreCards: (n) => `${n} carta${n !== 1 ? 's' : ''} más`,
  ready: "¡Listo!",
  goBack: "← Volver",
  confirmDiscard: "Confirmar descarte",
  addHatModal: "➕ Agregar Sombrero — descartás toda tu mano",
  addHatDesc: (max) => `Elige un sombrero del perchero para agregarlo a tu sombrero principal. Descartás toda tu mano y tu máximo de cartas se reduce en 1 (a ${max}). ¡Este efecto es acumulable! ¡Solo podrás jugar una carta de ingrediente después!`,
  trashBin: "🗑️ El Basurero — Elige una carta del descarte",
  trashBinDesc: "Rescata un ingrediente del montón de descarte.",
  wildcard: "🌭 Comodín — Elige ingrediente",
  wildcardNeeded: "Estos son los ingredientes que te faltan:",
  wildcardAny: "Elige el ingrediente que representa el comodín:",
  wildcardActingAs: (name) => `Comodín actuando como: ${name}`,
  wildcardCanBe: "Puede representar cualquier ingrediente",
  names: "Nombres",
  affectingCards: "Cartas que lo afectan",
  negation: "🚫 ¿Negación?",
  negationPlayed: (player, card) => `<strong>${player}</strong> jugó <strong>${card}</strong>`,
  negationQuestion: "¿Quieres gastar una carta de Negación para cancelar esta acción?",
  deny: "🚫 Negar",
  allow: "✅ Dejar pasar",
  noMessages: "Sin mensajes aún",
  typeMessage: "Escribe un mensaje...",
  send: "Enviar",
  reconnecting: "Reconectando a la sala...",
  leftRoom: "Te has salido de la sala",
  roomLabel: "Sala",
  wantToReturn: "¿Deseas volver a la sala?",
  returnToRoom: "Volver a la sala",
  noGoLobby: "No, ir al lobby",
  gamePaused: "Juego en pausa",
  aloneTitle: "Eres el único en la sala",
  aloneDesc: "Todos los demás jugadores se han ido",
  backToLobby: "Volver al lobby",
  espanol: "Español",
  ingles: "Inglés",
  frances: "Francés",
  italiano: "Italiano",
  aleman: "Alemán",
  portugues: "Portugués",
  langLabel: "Idioma",
  friends: "Amigos",
  friendsList: "Lista de amigos",
  friendRequests: "Solicitudes",
  addFriend: "Agregar amigo",
  searchUsers: "Buscar usuario...",
  sendRequest: "Enviar solicitud",
  requestSent: "Solicitud enviada",
  noFriends: "No tienes amigos aún",
  onlineStatus: "En línea",
  offlineStatus: "Desconectado",
  accept: "Aceptar",
  decline: "Rechazar",
  removeFriend: "Eliminar",
  inviteFriend: "Invitar amigo",
  inviteSent: "Invitación enviada",
  roomInvite: "Te invitó a una sala",
  joinRoom: "Unirse",
  noRequests: "Sin solicitudes pendientes",
  noResults: "Sin resultados",
  alreadyFriends: "Ya son amigos",
  requestAlreadySent: "Solicitud ya enviada",
  autoAccepted: "Aceptado automáticamente",
  blockUser: "Bloquear",
  unblockUser: "Desbloquear",
  blockedUsers: "Bloqueados",
  noBlocked: "Sin usuarios bloqueados",
  inviteToRoom: "Invitar a sala",
  friendAccepted: "aceptó tu solicitud",
  friendRemovedNotif: "dejó de ser tu amigo",
  friendRequestNotif: "te envió solicitud de amistad",
  viewRequest: "Ver",
  addFriendShort: "Agregar",
  profileMenu: "Perfil",
  leaveLocal: "Salir partida",
  leaveLocalConfirm: "¿Salir de la partida contra la IA y volver al setup?",
  homeMenu: "Inicio"
};

export default es;
