const fr = {
  appTitle: "HUNGRY POLY",
  tagline: "Apprends du vocabulaire en préparant des hamburgers",
  login: "Se connecter",
  register: "S'inscrire",
  username: "Utilisateur",
  password: "Mot de passe",
  displayName: "Nom d'affichage",
  loading: "Chargement...",
  enter: "Entrer",
  createAccount: "Créer un compte",
  playAsGuest: "Jouer en tant qu'invité",
  vsAiModePickerTitle: "Choisis ta partie contre IA",
  vsAiModePickerDesc: "Tu peux commencer une partie normale ou apprendre d abord avec le tutoriel.",
  vsAiModePickerNormalLabel: "Partie simple",
  vsAiModePickerNormalNeedHat: "Configure ton mode et choisis ton chapeau pour pouvoir jouer.",
  vsAiModePickerNormalReady: "Affronte les IA dans ce mode.",
  vsAiModePickerTutorialLabel: "Tutoriel",
  vsAiModePickerTutorialDesc: "Apprends les bases du jeu ici.",
  yourName: "TON NOM",
  enterName: "Entre ton nom...",
  chooseLanguage: "CHOISIS TA LANGUE",
  gameMode: "MODE DE JEU",
  modeClon: "Clone",
  modeEscalera: "Escalier",
  modeCaotico: "Chaotique",
  modeClonDesc: "Toutes pareilles",
  modeEscaleraDesc: "Ascendant",
  modeCaoticoDesc: "Tout aléatoire!",
  burgerCount: "HAMBURGERS",
  ingredientCount: "INGRÉDIENTS PAR BURGER",
  cloneIngredientPool: "PIÈCE D'INGRÉDIENTS",
  cloneIngredientPoolHint: "Choisis quels ingrédients peuvent apparaître dans les burgers du mode Clone.",
  cloneIngredientPoolLocked: "Le pain est toujours inclus.",
  cloneRemovedActions: "CARTES ACTION RETIRÉES",
  cloneRemovedActionsNone: "Cette sélection ne retire aucune carte action.",
  ingredientsLabelShort: "INGRÉDIENTS",
  perPlayerLabel: "PAR JOUEUR",
  aiOpponents: "ADVERSAIRES IA",
  cloneWildcardsToggle: "JOKERS DANS LE PAQUET",
  cloneWildcardsOn: "Jokers activés",
  cloneWildcardsOff: "Jokers désactivés",
  addAiPlayer: "Ajouter IA",
  cloneRemovedActionsLabel: "Cartes action retirées",
  cloneNoRemovedActions: "Aucune carte action n'est retirée",
  removeAiPlayer: "Retirer IA",
  aiDifficulty: "DIFFICULTÉ IA",
  aiEasy: "Facile",
  aiMedium: "Moyenne",
  aiHard: "Difficile",
  aiImpossible: "Impossible",
  opponent1: "1 adversaire",
  opponents3: "3 adversaires",
  vsAI: "🎮 vs IA",
  online: "🌐 En ligne",
  history: "Historique",
  logout: "Déconnexion",
  back: "← Retour",
  gameHistory: "Historique des Parties",
  games: "PARTIES",
  wins: "VICTOIRES",
  losses: "DÉFAITES",
  winrate: "WINRATE",
  all: "Toutes",
  winsFilter: "Victoires",
  lossesFilter: "Défaites",
  noGames: "Aucune partie enregistrée",
  victory: "Victoire",
  defeatBy: (name) => `Défaite — ${name} a gagné`,
  multiplayerOnline: "Multijoueur en Ligne",
  playWithFriends: "Joue avec des amis en temps réel",
  createRoom: "➕ Créer salon",
  lobby: "🏠 Lobby",
  code: "🔑 Code",
  roomType: "TYPE DE SALON",
  private: "🔒 Privé",
  codeOnly: "Code uniquement",
  public: "🌐 Public",
  visibleInLobby: "Visible dans le lobby",
  roomName: "NOM DU SALON",
  roomNamePlaceholder: "Ex: Partie rapide",
  creating: "⏳ Création...",
  createRoomBtn: "🎮 Créer salon",
  publicRooms: "SALONS PUBLICS",
  loadingRooms: "⏳ Chargement des salons...",
  noPublicRooms: "Il n’y a aucun salon actif",
  filterByMode: "Filtrer par mode",
  noPublicRoomsForMode: "Aucun salon public pour ce mode",
  createYourRoom: "Crée ton salon",
  players: "joueurs",
  join: "Rejoindre",
  roomCode: "CODE DU SALON",
  roomCodePlaceholder: "Ex: ABCD1",
  joining: "⏳ Connexion...",
  joinBtn: "🔗 Rejoindre",
  timeout: "Délai expiré. Réessaie.",
  enterNameFirst: "Entre ton nom d'abord",
  backToMenu: "← Retour au menu",
  publicRoom: "🌐 SALON PUBLIC",
  privateRoom: "🔒 CODE DU SALON",
  codeLabel: "Code",
  shareCode: "Partage ce code ou lien avec tes amis",
  linkCopied: "✅ Lien copié !",
  inviteLink: "🔗 Inviter avec lien",
  playersCount: (n) => `JOUEURS (${n}/6)`,
  you: "(toi)",
  host: "👑 Hôte",
  waitingPlayers: "⏳ En attente de joueurs...",
  yourLanguage: "TA LANGUE",
  chooseOne: "(choisis-en une)",
  waitingHats: (n, total) => `⏳ En attente des chapeaux (${n}/${total})`,
  startGame: "🚀 Lancer la partie !",
  chooseHat: "👆 Choisis ton chapeau de langue",
  waitingHost: "⏳ En attente du lancement...",
  leaveRoom: "← Quitter le salon",
  extraPlayMsg: "Tu peux jouer un ingrédient !",
  yourTurn: "Ton tour",
  turnOfPlayer: (name) => `Tour de ${name}`,
  tapContinue: "Touche pour continuer...",
  playerWon: (name) => `${name} a gagné !`,
  wonByAbandon: "Victoire par abandon !",
  abandonSubtitle: (name) => `${name} a quitté la partie.`,
  youLost: "Tu as perdu !",
  completedBurgers: "A complété tous ses hamburgers en premier",
  playAgain: "🔄 Rejouer",
  historyBtn: "📊 Historique",
  yourTurnLabel: "🎴 Ton tour",
  turnActionsLabel: "Que puis-je faire ?",
  actionName_milanesa: "La Milanesa",
  actionDesc_milanesa: "Tous défaussent pain et œuf",
  actionName_ensalada: "La Salade",
  actionDesc_ensalada: "Tous défaussent fruits/légumes",
  actionName_pizza: "La Pizza",
  actionDesc_pizza: "Tous défaussent fromage",
  actionName_parrilla: "Le Grill",
  actionDesc_parrilla: "Tous défaussent poulet et viande",
  actionName_tenedor: "La Fourchette",
  actionDesc_tenedor: "Vole un ingrédient à un joueur",
  actionName_ladron: "Voleur de Chapeaux",
  actionDesc_ladron: "Vole un chapeau principal",
  actionName_intercambio_sombreros: "Échange de Chapeaux",
  actionDesc_intercambio_sombreros: "Échange les chapeaux",
  actionName_intercambio_hamburguesa: "Échange de Table",
  actionDesc_intercambio_hamburguesa: "Échange les ingrédients de table",
  actionName_perchero_cubierto: "Penderie Couverte",
  actionDesc_perchero_cubierto: "Bloque changer/ajouter et les cartes de chapeau pendant un tour",
  actionName_basurero: "La Poubelle",
  actionDesc_basurero: "Récupère depuis la défausse",
  actionName_gloton: "Le Glouton",
  actionDesc_gloton: "Vide la table d’un joueur",
  actionName_negacion: "Négation",
  actionDesc_negacion: "Bloque une action ennemie",
  actionName_comecomodines: "Mange-Jokers",
  actionDesc_comecomodines: "Tous défaussent leurs jokers de table",
  actionNoObjectives: "Aucun objectif trouvé pour cette carte",
  closetCoverPrompt: (name) => name + ' a couvert ta penderie. Veux-tu défausser 2 cartes pour éviter l\'effet ?',
  closetCoverChooseTwo: "Choisis 2 cartes de ta main pour éviter cette carte.",
  closetCoverDiscardTwo: "Défausser 2 et éviter",
  closetCoverAccept: "Accepter l'effet",
  closetCoveredStatus: "Penderie couverte",
  howToPlayDesc: "Guide rapide du tour : utilise des cartes ingrédient pour compléter ton burger et des cartes action pour influencer la partie.",
  howToPlayPage: "Page",
  howToPlayTurnRulesTitle: "Règles du tour",
  howToPlayModeIntro: "Chaque partie utilise un mode différent. Ici tu peux voir lequel est actif maintenant et ce qui change dans l’objectif.",
  currentModeBadge: "Actuel",
  modeClonDetailed: "Tous les joueurs reçoivent exactement les mêmes burgers objectifs. La difficulté vient de la course pour les terminer avant les autres, pas d’objectifs différents.",
  modeEscaleraDetailed: "Tes burgers grandissent du plus simple au plus complexe. Tu commences avec des objectifs faciles puis chaque burger suivant demande plus d’ingrédients.",
  modeCaoticoDetailed: "Le nombre de burgers et les ingrédients requis changent de façon plus imprévisible. C’est le mode le plus variable et il peut produire des parties courtes ou très exigeantes.",
  howToPlayRuleOneCard: "Par tour, tu ne peux jouer qu’une carte : ingrédient ou action.",
  howToPlayRuleHatButtonsBeforePlay: "Les boutons Changer et Ajouter ne peuvent être utilisés qu’avant de jouer une carte.",
  howToPlayRuleHatButtonsIngredientOnly: "Si tu utilises Changer ou Ajouter, tu ne peux ensuite jouer qu’une carte ingrédient.",
  howToPlayIngredientTitle: "Carte Ingrédient",
  howToPlayIngredientDesc: "La carte ingrédient doit correspondre à ton chapeau principal et être un ingrédient dont ton burger a encore besoin.",
  howToPlayActionTitle: "Carte Action",
  howToPlayActionDesc: "Les cartes action te permettent de voler, échanger ou bloquer selon l’icône de chaque carte.",
  howToPlayActionSingleTitle: "Icône une personne",
  howToPlayActionSingleDesc: "Cette action affecte un seul joueur.",
  howToPlayActionGlobalTitle: "Icône plusieurs personnes",
  howToPlayActionGlobalDesc: "Cette action affecte tous les autres joueurs.",
  howToPlayActionDiscardTitle: "Icône cartes",
  howToPlayActionDiscardDesc: "Cette action sert à récupérer un ingrédient de la défausse.",
  howToPlayActionNegationTitle: "Icône X",
  howToPlayActionNegationDesc: "C’est la carte Négation.",
  howToPlayOthersDiscardLabel: "Les autres défaussent :",
  howToPlayEffectLabel: "Effet :",
  howToPlayEffectTenedor: "Tu voles 1 ingrédient sur la table d’un joueur.",
  howToPlayEffectLadron: "Tu voles le chapeau principal d’un joueur.",
  howToPlayEffectIntercambioSombreros: "Tu échanges les chapeaux avec un joueur.",
  howToPlayEffectIntercambioMesa: "Tu échanges ta table d’ingrédients avec celle d’un joueur.",
  howToPlayEffectGloton: "Tu vides la table d’ingrédients d’un joueur.",
  howToPlayGoalTitle: "Objectif du jeu",
  howToPlayEffectPercheroCubierto: "Bloque la penderie d'un autre joueur pendant son prochain tour, sauf s'il défausse 2 cartes en la recevant.",
  howToPlayGoalDesc: "Le gagnant est celui qui complète en premier tous ses burgers objectifs.",
  howToPlayMainHatsTitle: "Chapeaux principaux",
  howToPlayMainHatsDesc: "Tes chapeaux principaux déterminent quelles cartes ingrédient tu peux jouer pendant ton tour.",
  howToPlayHatButtonsTitle: "Boutons du chapeau principal",
  howToPlayChangeHatRule: "Changer : utilise-le avant de jouer ; après, tu ne pourras jouer qu’un ingrédient.",
  howToPlayAddHatRule: "Ajouter : utilise-le avant de jouer ; après, tu ne pourras jouer qu’un ingrédient.",
  howToPlayClosetTitle: "Porte-chapeaux",
  howToPlayClosetDesc: (n) => `Ici tu gardes des chapeaux supplémentaires pour changer ou ajouter. Tu en as actuellement ${n}.`,
  prevPage: "Précédent",
  nextPage: "Suivant",
  howToPlayActionPageSingle: "Actions : un joueur",
  howToPlayActionPageGlobal: "Actions : tous les autres joueurs",
  howToPlayActionPageNegDiscard: "Actions : négation et défausse",
  tiPlayIngDesc: "Joue une carte ingrédient qui correspond à ton chapeau principal et dont ton burger a besoin.",
  tiPlayCardDesc: "Joue une carte action (⚡) pour affecter les adversaires. Ils peuvent la bloquer avec Négation 🚫 !",
  tiDiscardDesc: "Défausse n'importe quelle carte de ta main pour terminer ton tour. Ta main se remplit automatiquement.",
  extraPlayLabel: "🍔 Tu peux ajouter un ingrédient",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Salon",
  log: "📋 Log",
  chat: "💬 Chat",
  leave: "🚪 Quitter",
  opponents: "ADVERSAIRES",
  historyLog: "HISTORIQUE",
  noEvents: "Aucun événement",
  burgers: "HAMBURGERS",
  table: "TABLE",
  tableCount: (n) => `TABLE (${n} ingrédients)`,
  emptyTable: "Table vide",
  sharedGoalsLabel: "Objectifs partagés",
  mainHat: "PRINCIPAL",
  closet: "PENDERIE",
  viewCloset: (n) => `🧥 Voir penderie (${n})`,
  changeHat: "🎩 Changer",
  changeHatTooltip: "Change ton chapeau principal (coûte la moitié de ta main)",
  addHat: "➕ Ajouter",
  addHatTooltip: "Ajoute un chapeau (défausse toute ta main, max réduit)",
  hand: "MAIN",
  maxReduced: "Max réduit par ajout",
  canPlay: "✅ Jouable",
  cantPlay: "❌ Non jouable",
  cantPlayNow: "❌ Impossible de jouer cette carte maintenant",
  canPlayThis: "✅ Tu peux jouer cette carte",
  play: "▶ Jouer",
  discard: "🗑 Défausser",
  skipTurn: "⏭ Passer le tour",
  waitingOnline: (name) => `🌐 En attente du coup de ${name}...`,
  waitingLocal: (name) => `⏳ En attente de ${name}...`,
  cardsInHand: (n) => `🃏 ${n} cartes en main`,
  turn: "⟵ tour",
  wildcardChoose: "Choisis l'ingrédient dont tu as besoin",
  ingredientCard: "🃏 Carte Ingrédient",
  ingredientTag: "Ingrédient",
  actionCard: "⚡ Carte Action",
  tableTab: "🍔 Table",
  rivalsTab: "👥 Rivaux",
  chatTab: "💬 Chat",
  chooseOpponent: "Choisis un adversaire",
  tableLabel: "Table",
  empty: "vide",
  burgersLabel: "Hamburgers",
  cancel: "Annuler",
  forkSteal: "🍴 La Fourchette — Choisis un ingrédient à voler",
  chooseNewHat: "🎩 Choisis un nouveau chapeau principal",
  waitingHatChoice: (name) => `⏳ En attente du choix de ${name}...`,
  hatStolen: "Ton chapeau principal a été volé. Choisis-en un dans la penderie.",
  hatExchange: "🔄 Échange de Chapeaux",
  hatExchangeDesc: (name) => `Choisis le chapeau à donner et celui à recevoir de ${name}.`,
  yourHatToGive: "Ton chapeau à donner :",
  hatToReceive: (name) => `Chapeau que tu veux de ${name} :`,
  exchange: "Échanger",
  close: "Fermer",
  changeHatStep1: "🎩 Changer Chapeau — étape 1 : choisir chapeau",
  changeHatStep1Desc: (n) => `Choisis un chapeau de la penderie. Ensuite tu choisiras ${n} carte${n !== 1 ? 's' : ''} à défausser.`,
  changeHatStep2: (lang) => `🎩 Changer pour ${lang} — étape 2 : choisir cartes`,
  changeHatStep2SelectMain: (lang) => `Changer pour ${lang} - étape 2 : choisir le principal`,
  changeHatStep2Desc: (lang) => `Choisis quel chapeau principal tu veux remplacer par ${lang}.`,
  changeHatNewPrimaryHint: "C'est le nouveau chapeau que tu vas placer dans tes chapeaux principaux.",
  changeHatStep3ChooseCards: (lang) => `vers ${lang} - étape 3 : choisir cartes`,
  changeHatNoUsefulCards: "Tu n'as pas de cartes utiles pour ce chapeau.",
  changeHatProceedAnyway: "Changer quand même",
  moreCards: (n) => `${n} carte${n !== 1 ? 's' : ''} de plus`,
  ready: "Prêt !",
  goBack: "← Retour",
  confirmDiscard: "Confirmer la défausse",
  addHatModal: "➕ Ajouter Chapeau — défausse toute ta main",
  addHatDesc: (max) => `Choisis un chapeau de la penderie. Tu défausses toute ta main et ton max de cartes est réduit de 1 (à ${max}).`,
  trashBin: "🗑️ La Poubelle — Choisis une carte de la défausse",
  trashBinDesc: "Récupère un ingrédient de la pile de défausse.",
  wildcard: "🌭 Joker — Choisis un ingrédient",
  wildcardNeeded: "Voici les ingrédients qu'il te manque :",
  wildcardAny: "Choisis l'ingrédient que représente le joker :",
  wildcardActingAs: (name) => `Joker comme : ${name}`,
  wildcardCanBe: "Peut représenter n'importe quel ingrédient",
  names: "Noms",
  affectingCards: "Cartes qui l'affectent",
  negation: "🚫 Négation ?",
  negationPlayed: (player, card) => `<strong>${player}</strong> a joué <strong>${card}</strong>`,
  negationQuestion: "Veux-tu utiliser une carte Négation pour annuler cette action ?",
  deny: "🚫 Nier",
  allow: "✅ Laisser passer",
  noMessages: "Aucun message",
  typeMessage: "Écris un message...",
  send: "Envoyer",
  reconnecting: "Reconnexion au salon...",
  leftRoom: "Tu as quitté le salon",
  roomLabel: "Salon",
  wantToReturn: "Veux-tu retourner au salon ?",
  returnToRoom: "Retourner au salon",
  noGoLobby: "Non, aller au lobby",
  gamePaused: "Partie en pause",
  aloneTitle: "Tu es seul dans le salon",
  aloneDesc: "Tous les autres joueurs sont partis",
  backToLobby: "Retour au lobby",
  espanol: "Espagnol",
  ingles: "Anglais",
  frances: "Français",
  italiano: "Italien",
  aleman: "Allemand",
  portugues: "Portugais",
  langLabel: "Langue",
  friends: "Amis",
  friendsList: "Liste d'amis",
  friendRequests: "Demandes",
  addFriend: "Ajouter un ami",
  searchUsers: "Chercher utilisateur...",
  sendRequest: "Envoyer demande",
  requestSent: "Demande envoyée",
  noFriends: "Pas encore d'amis",
  onlineStatus: "En ligne",
  offlineStatus: "Hors ligne",
  accept: "Accepter",
  decline: "Refuser",
  removeFriend: "Supprimer",
  inviteFriend: "Inviter un ami",
  inviteSent: "Invitation envoyée",
  roomInvite: "t'a invité dans une salle",
  joinRoom: "Rejoindre",
  noRequests: "Aucune demande en attente",
  noResults: "Aucun résultat",
  alreadyFriends: "Déjà amis",
  requestAlreadySent: "Demande déjà envoyée",
  autoAccepted: "Accepté automatiquement",
  blockUser: "Bloquer",
  unblockUser: "Débloquer",
  blockedUsers: "Bloqués",
  noBlocked: "Aucun utilisateur bloqué",
  inviteToRoom: "Inviter dans la salle",
  friendAccepted: "a accepté ta demande",
  friendRemovedNotif: "n'est plus ton ami",
  friendRequestNotif: "t'a envoyé une demande d'ami",
  viewRequest: "Voir",
  addFriendShort: "Ajouter",
  profileMenu: "Profil",
  leaveLocal: "Quitter la partie",
  leaveLocalConfirm: "Quitter la partie contre l’IA et revenir au setup ?",
  homeMenu: "Accueil",
  gameLanguageMenu: "Langue du jeu"
};

export default fr;
