const en = {
  appTitle: "HUNGRY POLY",
  tagline: "Learn vocabulary by building burgers",
  login: "Log In",
  register: "Sign Up",
  username: "Username",
  password: "Password",
  displayName: "Display name",
  loading: "Loading...",
  enter: "Log In",
  createAccount: "Create account",
  playAsGuest: "Play as guest",
  vsAiModePickerTitle: "Choose your vs AI match",
  vsAiModePickerDesc: "You can start a normal match or learn first with the tutorial.",
  vsAiModePickerNormalLabel: "Simple match",
  vsAiModePickerNormalNeedHat: "Set your mode and choose your hat to start playing.",
  vsAiModePickerNormalReady: "Face the AIs in this mode.",
  vsAiModePickerTutorialLabel: "Tutorial",
  vsAiModePickerTutorialDesc: "Learn the basics of the game here.",
  yourName: "YOUR NAME",
  enterName: "Enter your name...",
  chooseLanguage: "CHOOSE YOUR LANGUAGE",
  gameMode: "GAME MODE",
  modeClon: "Clone",
  modeEscalera: "Staircase",
  modeCaotico: "Chaotic",
  modeClonDesc: "All equal",
  modeEscaleraDesc: "Ascending",
  modeCaoticoDesc: "All random!",
  burgerCount: "BURGERS",
  ingredientCount: "INGREDIENTS PER BURGER",
  cloneIngredientPool: "INGREDIENT POOL",
  cloneIngredientPoolHint: "Choose which ingredients can appear in Clone mode burgers.",
  cloneIngredientPoolLocked: "Bread is always included.",
  cloneRemovedActions: "REMOVED ACTION CARDS",
  cloneRemovedActionsNone: "This selection removes no action cards.",
  ingredientsLabelShort: "INGREDIENTS",
  perPlayerLabel: "PER PLAYER",
  aiOpponents: "AI OPPONENTS",
  cloneWildcardsToggle: "WILDCARDS IN DECK",
  cloneWildcardsOn: "Wildcards enabled",
  cloneWildcardsOff: "Wildcards disabled",
  addAiPlayer: "Add AI",
  cloneRemovedActionsLabel: "Removed action cards",
  cloneNoRemovedActions: "No action cards are removed",
  removeAiPlayer: "Remove AI",
  aiDifficulty: "AI DIFFICULTY",
  aiEasy: "Easy",
  aiMedium: "Medium",
  aiHard: "Hard",
  aiImpossible: "Impossible",
  opponent1: "1 opponent",
  opponents3: "3 opponents",
  vsAI: "🎮 vs AI",
  online: "🌐 Online",
  history: "History",
  logout: "Log out",
  back: "← Back",
  gameHistory: "Game History",
  games: "GAMES",
  wins: "WINS",
  losses: "LOSSES",
  winrate: "WINRATE",
  all: "All",
  winsFilter: "Wins",
  lossesFilter: "Losses",
  noGames: "No games recorded",
  victory: "Victory",
  defeatBy: (name) => `Defeat — ${name} won`,
  multiplayerOnline: "Online Multiplayer",
  playWithFriends: "Play with friends in real time",
  createRoom: "➕ Create room",
  lobby: "🏠 Lobby",
  code: "🔑 Code",
  roomType: "ROOM TYPE",
  private: "🔒 Private",
  codeOnly: "Code only",
  public: "🌐 Public",
  visibleInLobby: "Visible in lobby",
  roomName: "ROOM NAME",
  roomNamePlaceholder: "E.g.: Quick match",
  creating: "⏳ Creating...",
  createRoomBtn: "🎮 Create room",
  publicRooms: "PUBLIC ROOMS",
  loadingRooms: "⏳ Loading rooms...",
  noPublicRooms: "There are no active rooms",
  filterByMode: "Filter by mode",
  noPublicRoomsForMode: "No public rooms available for that mode",
  createYourRoom: "Create your room",
  players: "players",
  join: "Join",
  roomCode: "ROOM CODE",
  roomCodePlaceholder: "E.g.: ABCD1",
  joining: "⏳ Joining...",
  joinBtn: "🔗 Join",
  timeout: "Timed out. Please try again.",
  enterNameFirst: "Enter your name first",
  backToMenu: "← Back to menu",
  publicRoom: "🌐 PUBLIC ROOM",
  privateRoom: "🔒 ROOM CODE",
  codeLabel: "Code",
  shareCode: "Share this code or link with your friends",
  linkCopied: "✅ Link copied!",
  inviteLink: "🔗 Invite with link",
  playersCount: (n) => `PLAYERS (${n}/6)`,
  you: "(you)",
  host: "👑 Host",
  waitingPlayers: "⏳ Waiting for more players...",
  yourLanguage: "YOUR LANGUAGE",
  chooseOne: "(choose one)",
  waitingHats: (n, total) => `⏳ Waiting for hats (${n}/${total})`,
  startGame: "🚀 Start game!",
  chooseHat: "👆 Choose your language hat",
  waitingHost: "⏳ Waiting for host to start...",
  leaveRoom: "← Leave room",
  extraPlayMsg: "You can play an ingredient!",
  yourTurn: "Your turn",
  turnOfPlayer: (name) => `${name}'s turn`,
  tapContinue: "Tap to continue...",
  playerWon: (name) => `${name} won!`,
  wonByAbandon: "You win by abandonment!",
  abandonSubtitle: (name) => `${name} left the match.`,
  youLost: "You lost!",
  completedBurgers: "Completed all burgers first",
  playAgain: "🔄 Play again",
  historyBtn: "📊 History",
  yourTurnLabel: "🎴 Your turn",
  turnActionsLabel: "What can I do?",
  actionName_milanesa: "The Milanesa",
  actionDesc_milanesa: "Everyone discards bread and egg",
  actionName_ensalada: "The Salad",
  actionDesc_ensalada: "Everyone discards fruits/veggies",
  actionName_pizza: "The Pizza",
  actionDesc_pizza: "Everyone discards cheese",
  actionName_parrilla: "The Grill",
  actionDesc_parrilla: "Everyone discards chicken and beef",
  actionName_tenedor: "The Fork",
  actionDesc_tenedor: "Steal ingredient from another player",
  actionName_ladron: "Hat Thief",
  actionDesc_ladron: "Steal a main hat",
  actionName_intercambio_sombreros: "Hat Swap",
  actionDesc_intercambio_sombreros: "Swap hats with a player",
  actionName_intercambio_hamburguesa: "Table Swap",
  actionDesc_intercambio_hamburguesa: "Swap ingredient tables",
  actionName_perchero_cubierto: "Covered Closet",
  actionDesc_perchero_cubierto: "Blocks closet actions and hat cards for one turn",
  actionName_basurero: "Trash Bin",
  actionDesc_basurero: "Recover from discard pile",
  actionName_gloton: "The Glutton",
  actionDesc_gloton: "Empty another player table",
  actionName_negacion: "Negation",
  actionDesc_negacion: "Block an enemy action",
  actionName_comecomodines: "Wildcard Eater",
  actionDesc_comecomodines: "Everyone discards wildcards from table",
  actionNoObjectives: "No objectives found for this card",
  closetCoverPrompt: (name) => name + ' covered your closet. Do you want to discard 2 cards to avoid the effect?',
  closetCoverChooseTwo: "Choose 2 cards from your hand to avoid this card.",
  closetCoverDiscardTwo: "Discard 2 and avoid",
  closetCoverAccept: "Accept effect",
  closetCoveredStatus: "Closet covered",
  howToPlayDesc: "Quick turn guide: use ingredient cards to complete your burger and action cards to affect the match.",
  howToPlayPage: "Page",
  howToPlayTurnRulesTitle: "Turn rules",
  howToPlayModeIntro: "Each match uses a different mode. Here you can see which one is active now and what changes in the objective.",
  currentModeBadge: "Current",
  modeClonDetailed: "All players receive exactly the same target burgers. The challenge is racing to complete them before everyone else, not dealing with different orders.",
  modeEscaleraDetailed: "Your burgers grow from smaller to larger. You begin with simpler goals and each next burger asks for more ingredients, so the match ramps up progressively.",
  modeCaoticoDetailed: "The number of burgers and the ingredients required change in a more unpredictable way. It is the most variable mode and can create either short or very demanding matches.",
  howToPlayRuleOneCard: "Per turn you can play only one card: ingredient or action.",
  howToPlayRuleHatButtonsBeforePlay: "Change and Add can only be used before you play a card.",
  howToPlayRuleHatButtonsIngredientOnly: "If you use Change or Add, then you can only play one ingredient card.",
  howToPlayIngredientTitle: "Ingredient Card",
  howToPlayIngredientDesc: "An ingredient card must match your main hat and be an ingredient your burger still needs.",
  howToPlayActionTitle: "Action Card",
  howToPlayActionDesc: "Action cards let you steal, swap, or block plays based on each card icon.",
  howToPlayActionSingleTitle: "Single-player icon",
  howToPlayActionSingleDesc: "This action affects one player.",
  howToPlayActionGlobalTitle: "Multi-player icon",
  howToPlayActionGlobalDesc: "This action affects all other players.",
  howToPlayActionDiscardTitle: "Cards icon",
  howToPlayActionDiscardDesc: "This action lets you recover an ingredient from discard.",
  howToPlayActionNegationTitle: "X icon",
  howToPlayActionNegationDesc: "This is the Negation card.",
  howToPlayOthersDiscardLabel: "Others discard:",
  howToPlayEffectLabel: "Effect:",
  howToPlayEffectTenedor: "Steal 1 ingredient from a player table.",
  howToPlayEffectLadron: "Steal a player main hat.",
  howToPlayEffectIntercambioSombreros: "Swap hats with a player.",
  howToPlayEffectIntercambioMesa: "Swap your ingredient table with another player.",
  howToPlayEffectGloton: "Empty one player ingredient table.",
  howToPlayGoalTitle: "Game objective",
  howToPlayEffectPercheroCubierto: "Blocks another player closet during their next turn, unless they discard 2 cards when they receive it.",
  howToPlayGoalDesc: "The winner is whoever completes all target burgers first.",
  howToPlayMainHatsTitle: "Main hats",
  howToPlayMainHatsDesc: "Your main hats determine which ingredient cards you can play on your turn.",
  howToPlayHatButtonsTitle: "Main hat buttons",
  howToPlayChangeHatRule: "Change: use before playing; after that you can only play 1 ingredient.",
  howToPlayAddHatRule: "Add: use before playing; after that you can only play 1 ingredient.",
  howToPlayClosetTitle: "Closet",
  howToPlayClosetDesc: (n) => `Here you store extra hats to change or add. You currently have ${n}.`,
  prevPage: "Previous",
  nextPage: "Next",
  howToPlayActionPageSingle: "Actions: one player",
  howToPlayActionPageGlobal: "Actions: all other players",
  howToPlayActionPageNegDiscard: "Actions: negation and discard",
  tiPlayIngDesc: "Play an ingredient card that matches your main hat and that your burger needs.",
  tiPlayCardDesc: "Play an action card (⚡) to affect opponents. They can block it with Negation 🚫!",
  tiDiscardDesc: "Discard any card from your hand to end your turn. Your hand refills automatically.",
  extraPlayLabel: "🍔 You can add an ingredient",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Room",
  log: "📋 Log",
  chat: "💬 Chat",
  leave: "🚪 Leave",
  opponents: "OPPONENTS",
  historyLog: "HISTORY",
  noEvents: "No events yet",
  burgers: "BURGERS",
  table: "TABLE",
  tableCount: (n) => `TABLE (${n} ingredients)`,
  emptyTable: "Empty table",
  sharedGoalsLabel: "Shared goals",
  mainHat: "MAIN",
  closet: "CLOSET",
  viewCloset: (n) => `🧥 View closet (${n})`,
  changeHat: "🎩 Change",
  changeHatTooltip: "Change your main hat (costs discarding half your hand)",
  addHat: "➕ Add",
  addHatTooltip: "Add an extra hat (discard entire hand, max hand reduced)",
  hand: "HAND",
  maxReduced: "Max reduced from adding",
  canPlay: "✅ Can play",
  cantPlay: "❌ Cannot play",
  cantPlayNow: "❌ Cannot play this card now (hat or ingredient not needed)",
  canPlayThis: "✅ You can play this card",
  play: "▶ Play",
  discard: "🗑 Discard",
  skipTurn: "⏭ Skip turn",
  waitingOnline: (name) => `🌐 Waiting for ${name}'s move...`,
  waitingLocal: (name) => `⏳ Waiting for ${name}...`,
  cardsInHand: (n) => `🃏 ${n} cards in hand`,
  turn: "⟵ turn",
  wildcardChoose: "Choose the ingredient you need",
  ingredientCard: "🃏 Ingredient Card",
  ingredientTag: "Ingredient",
  actionCard: "⚡ Action Card",
  tableTab: "🍔 Table",
  rivalsTab: "👥 Rivals",
  chatTab: "💬 Chat",
  chooseOpponent: "Choose opponent",
  tableLabel: "Table",
  empty: "empty",
  burgersLabel: "Burgers",
  cancel: "Cancel",
  forkSteal: "🍴 The Fork — Choose ingredient to steal",
  chooseNewHat: "🎩 Choose new main hat",
  waitingHatChoice: (name) => `⏳ Waiting for ${name} to choose their hat...`,
  hatStolen: "Your main hat was stolen. Choose one from the closet.",
  hatExchange: "🔄 Hat Exchange",
  hatExchangeDesc: (name) => `Choose the hat to give and the one to receive from ${name}.`,
  yourHatToGive: "Your hat to give:",
  hatToReceive: (name) => `Hat you want from ${name}:`,
  exchange: "Exchange",
  close: "Close",
  changeHatStep1: "🎩 Change Hat — step 1: choose hat",
  changeHatStep1Desc: (n) => `Choose a hat from the closet. Then choose ${n} card${n !== 1 ? 's' : ''} to discard. You can only play one ingredient card after!`,
  changeHatStep2: (lang) => `🎩 Change to ${lang} — step 2: choose cards`,
  moreCards: (n) => `${n} more card${n !== 1 ? 's' : ''}`,
  ready: "Done!",
  goBack: "← Back",
  confirmDiscard: "Confirm discard",
  addHatModal: "➕ Add Hat — discard your entire hand",
  addHatDesc: (max) => `Choose a hat from the closet to add to your main hat. You discard your entire hand and max cards reduced by 1 (to ${max}). This effect stacks! You can only play one ingredient card after!`,
  trashBin: "🗑️ The Trash Bin — Choose a card from discard",
  trashBinDesc: "Rescue an ingredient from the discard pile.",
  wildcard: "🌭 Wildcard — Choose ingredient",
  wildcardNeeded: "These are the ingredients you need:",
  wildcardAny: "Choose the ingredient the wildcard represents:",
  wildcardActingAs: (name) => `Wildcard acting as: ${name}`,
  wildcardCanBe: "Can represent any ingredient",
  names: "Names",
  affectingCards: "Cards that affect it",
  negation: "🚫 Negate?",
  negationPlayed: (player, card) => `<strong>${player}</strong> played <strong>${card}</strong>`,
  negationQuestion: "Do you want to use a Negation card to cancel this action?",
  deny: "🚫 Negate",
  allow: "✅ Let it pass",
  noMessages: "No messages yet",
  typeMessage: "Type a message...",
  send: "Send",
  reconnecting: "Reconnecting to room...",
  leftRoom: "You left the room",
  roomLabel: "Room",
  wantToReturn: "Do you want to return to the room?",
  returnToRoom: "Return to room",
  noGoLobby: "No, go to lobby",
  gamePaused: "Game paused",
  aloneTitle: "You are alone in the room",
  aloneDesc: "All other players have left",
  backToLobby: "Back to lobby",
  espanol: "Spanish",
  ingles: "English",
  frances: "French",
  italiano: "Italian",
  aleman: "German",
  portugues: "Portuguese",
  langLabel: "Language",
  friends: "Friends",
  friendsList: "Friends list",
  friendRequests: "Requests",
  addFriend: "Add friend",
  searchUsers: "Search user...",
  sendRequest: "Send request",
  requestSent: "Request sent",
  noFriends: "No friends yet",
  onlineStatus: "Online",
  offlineStatus: "Offline",
  accept: "Accept",
  decline: "Decline",
  removeFriend: "Remove",
  inviteFriend: "Invite friend",
  inviteSent: "Invite sent",
  roomInvite: "invited you to a room",
  joinRoom: "Join",
  noRequests: "No pending requests",
  noResults: "No results",
  alreadyFriends: "Already friends",
  requestAlreadySent: "Request already sent",
  autoAccepted: "Auto-accepted",
  blockUser: "Block",
  unblockUser: "Unblock",
  blockedUsers: "Blocked",
  noBlocked: "No blocked users",
  inviteToRoom: "Invite to room",
  friendAccepted: "accepted your request",
  friendRemovedNotif: "removed you from friends",
  friendRequestNotif: "sent you a friend request",
  viewRequest: "View",
  addFriendShort: "Add",
  profileMenu: "Profile",
  leaveLocal: "Exit match",
  leaveLocalConfirm: "Exit the AI match and return to setup?",
  homeMenu: "Home",
  gameLanguageMenu: "Game language"
};

export default en;
