const it = {
  appTitle: "HUNGRY POLY",
  tagline: "Impara vocabolario preparando hamburger",
  login: "Accedi",
  register: "Registrati",
  username: "Utente",
  password: "Password",
  displayName: "Nome visualizzato",
  loading: "Caricamento...",
  enter: "Accedi",
  createAccount: "Crea account",
  playAsGuest: "Gioca come ospite",
  vsAiModePickerTitle: "Scegli la tua partita contro IA",
  vsAiModePickerDesc: "Puoi iniziare una partita normale oppure imparare prima con il tutorial.",
  vsAiModePickerNormalLabel: "Partita semplice",
  vsAiModePickerNormalNeedHat: "Configura la modalita e scegli il tuo cappello per poter giocare.",
  vsAiModePickerNormalReady: "Affronta le IA in questa modalita.",
  vsAiModePickerTutorialLabel: "Tutorial",
  vsAiModePickerTutorialDesc: "Impara qui le basi del gioco.",
  yourName: "IL TUO NOME",
  enterName: "Inserisci il tuo nome...",
  chooseLanguage: "SCEGLI LA TUA LINGUA",
  gameMode: "MODALITÀ DI GIOCO",
  modeClon: "Clone",
  modeEscalera: "Scaletta",
  modeCaotico: "Caotico",
  modeClonDesc: "Tutte uguali",
  modeEscaleraDesc: "Ascendente",
  modeCaoticoDesc: "Tutto casuale!",
  burgerCount: "HAMBURGER",
  ingredientCount: "INGREDIENTI PER BURGER",
  cloneIngredientPool: "POOL DI INGREDIENTI",
  cloneIngredientPoolHint: "Scegli quali ingredienti possono apparire negli hamburger della modalità Clone.",
  cloneIngredientPoolLocked: "Il pane è sempre incluso.",
  cloneRemovedActions: "CARTE AZIONE RIMOSSE",
  cloneRemovedActionsNone: "Questa selezione non rimuove nessuna carta azione.",
  ingredientsLabelShort: "INGREDIENTI",
  perPlayerLabel: "PER GIOCATORE",
  aiOpponents: "AVVERSARI IA",
  cloneWildcardsToggle: "JOLLY NEL MAZZO",
  cloneWildcardsOn: "Jolly attivi",
  cloneWildcardsOff: "Jolly disattivi",
  addAiPlayer: "Aggiungi IA",
  cloneRemovedActionsLabel: "Carte azione rimosse",
  cloneNoRemovedActions: "Nessuna carta azione viene rimossa",
  removeAiPlayer: "Rimuovi IA",
  aiDifficulty: "DIFFICOLTÀ IA",
  aiEasy: "Facile",
  aiMedium: "Media",
  aiHard: "Difficile",
  aiImpossible: "Impossibile",
  opponent1: "1 avversario",
  opponents3: "3 avversari",
  vsAI: "🎮 vs IA",
  online: "🌐 Online",
  history: "Cronologia",
  logout: "Esci",
  back: "← Indietro",
  gameHistory: "Cronologia Partite",
  games: "PARTITE",
  wins: "VITTORIE",
  losses: "SCONFITTE",
  winrate: "WINRATE",
  all: "Tutte",
  winsFilter: "Vittorie",
  lossesFilter: "Sconfitte",
  noGames: "Nessuna partita registrata",
  victory: "Vittoria",
  defeatBy: (name) => `Sconfitta — Ha vinto ${name}`,
  multiplayerOnline: "Multiplayer Online",
  playWithFriends: "Gioca con amici in tempo reale",
  createRoom: "➕ Crea stanza",
  lobby: "🏠 Lobby",
  code: "🔑 Codice",
  roomType: "TIPO DI STANZA",
  private: "🔒 Privata",
  codeOnly: "Solo con codice",
  public: "🌐 Pubblica",
  visibleInLobby: "Visibile nel lobby",
  roomName: "NOME STANZA",
  roomNamePlaceholder: "Es: Partita veloce",
  creating: "⏳ Creazione...",
  createRoomBtn: "🎮 Crea stanza",
  publicRooms: "STANZE PUBBLICHE",
  loadingRooms: "⏳ Caricamento stanze...",
  noPublicRooms: "Non ci sono stanze attive",
  filterByMode: "Filtra per modalità",
  noPublicRoomsForMode: "Nessuna stanza pubblica per questa modalità",
  createYourRoom: "Crea la tua stanza",
  players: "giocatori",
  join: "Unisciti",
  roomCode: "CODICE STANZA",
  roomCodePlaceholder: "Es: ABCD1",
  joining: "⏳ Connessione...",
  joinBtn: "🔗 Unisciti",
  timeout: "Tempo scaduto. Riprova.",
  enterNameFirst: "Inserisci prima il tuo nome",
  backToMenu: "← Torna al menu",
  publicRoom: "🌐 STANZA PUBBLICA",
  privateRoom: "🔒 CODICE STANZA",
  codeLabel: "Codice",
  shareCode: "Condividi questo codice o link con i tuoi amici",
  linkCopied: "✅ Link copiato!",
  inviteLink: "🔗 Invita con link",
  playersCount: (n) => `GIOCATORI (${n}/6)`,
  you: "(tu)",
  host: "👑 Host",
  waitingPlayers: "⏳ In attesa di altri giocatori...",
  yourLanguage: "LA TUA LINGUA",
  chooseOne: "(scegline una)",
  waitingHats: (n, total) => `⏳ In attesa dei cappelli (${n}/${total})`,
  startGame: "🚀 Inizia partita!",
  chooseHat: "👆 Scegli il tuo cappello",
  waitingHost: "⏳ In attesa che l'host inizi...",
  leaveRoom: "← Esci dalla stanza",
  extraPlayMsg: "Puoi giocare un ingrediente!",
  yourTurn: "Il tuo turno",
  turnOfPlayer: (name) => `Turno di ${name}`,
  tapContinue: "Tocca per continuare...",
  playerWon: (name) => `${name} ha vinto!`,
  wonByAbandon: "Hai vinto per abbandono!",
  abandonSubtitle: (name) => `${name} ha lasciato la partita.`,
  youLost: "Hai perso!",
  completedBurgers: "Ha completato tutti gli hamburger per primo",
  playAgain: "🔄 Gioca ancora",
  historyBtn: "📊 Cronologia",
  yourTurnLabel: "🎴 Il tuo turno",
  turnActionsLabel: "Cosa posso fare?",
  actionName_milanesa: "La Milanesa",
  actionDesc_milanesa: "Tutti scartano pane e uovo",
  actionName_ensalada: "L’Insalata",
  actionDesc_ensalada: "Tutti scartano frutta/verdura",
  actionName_pizza: "La Pizza",
  actionDesc_pizza: "Tutti scartano formaggio",
  actionName_parrilla: "La Griglia",
  actionDesc_parrilla: "Tutti scartano pollo e carne",
  actionName_tenedor: "La Forchetta",
  actionDesc_tenedor: "Ruba un ingrediente a un giocatore",
  actionName_ladron: "Ladro di Cappelli",
  actionDesc_ladron: "Ruba un cappello principale",
  actionName_intercambio_sombreros: "Scambio Cappelli",
  actionDesc_intercambio_sombreros: "Scambia i cappelli",
  actionName_intercambio_hamburguesa: "Scambio Tavolo",
  actionDesc_intercambio_hamburguesa: "Scambia ingredienti del tavolo",
  actionName_perchero_cubierto: "Armadio Coperto",
  actionDesc_perchero_cubierto: "Blocca cambia/aggiungi e le carte cappello per un turno",
  actionName_basurero: "Il Cestino",
  actionDesc_basurero: "Recupera dagli scarti",
  actionName_gloton: "Il Goloso",
  actionDesc_gloton: "Svuota il tavolo di un giocatore",
  actionName_negacion: "Negazione",
  actionDesc_negacion: "Blocca un’azione nemica",
  actionName_comecomodines: "Mangia Jolly",
  actionDesc_comecomodines: "Tutti scartano i jolly dal tavolo",
  actionNoObjectives: "Nessun obiettivo trovato per questa carta",
  closetCoverPrompt: (name) => name + ' ha coperto il tuo armadio. Vuoi scartare 2 carte per evitare l\'effetto?',
  closetCoverChooseTwo: "Scegli 2 carte dalla tua mano per evitare questa carta.",
  closetCoverDiscardTwo: "Scarta 2 ed evita",
  closetCoverAccept: "Accetta effetto",
  closetCoveredStatus: "Armadio coperto",
  howToPlayDesc: "Guida rapida del turno: usa carte ingrediente per completare il tuo burger e carte azione per influenzare la partita.",
  howToPlayPage: "Pagina",
  howToPlayTurnRulesTitle: "Regole del turno",
  howToPlayModeIntro: "Ogni partita usa una modalità diversa. Qui puoi vedere quale è attiva adesso e cosa cambia nell’obiettivo.",
  currentModeBadge: "Attuale",
  modeClonDetailed: "Tutti i giocatori ricevono esattamente gli stessi burger obiettivo. La difficoltà sta nel completarli prima degli altri, non nell’avere richieste diverse.",
  modeEscaleraDetailed: "I tuoi burger crescono da più semplici a più complessi. Inizi con obiettivi facili e ogni burger successivo richiede più ingredienti.",
  modeCaoticoDetailed: "Il numero di burger e gli ingredienti richiesti cambiano in modo più imprevedibile. È la modalità più variabile e può creare partite brevi o molto impegnative.",
  howToPlayRuleOneCard: "Per turno puoi giocare solo una carta: ingrediente o azione.",
  howToPlayRuleHatButtonsBeforePlay: "I pulsanti Cambia e Aggiungi si possono usare solo prima di giocare una carta.",
  howToPlayRuleHatButtonsIngredientOnly: "Se usi Cambia o Aggiungi, poi puoi giocare solo una carta ingrediente.",
  howToPlayIngredientTitle: "Carta Ingrediente",
  howToPlayIngredientDesc: "La carta ingrediente deve corrispondere al tuo cappello principale ed essere un ingrediente di cui il tuo burger ha ancora bisogno.",
  howToPlayActionTitle: "Carta Azione",
  howToPlayActionDesc: "Le carte azione ti permettono di rubare, scambiare o bloccare in base all’icona della carta.",
  howToPlayActionSingleTitle: "Icona una persona",
  howToPlayActionSingleDesc: "Questa azione colpisce un solo giocatore.",
  howToPlayActionGlobalTitle: "Icona più persone",
  howToPlayActionGlobalDesc: "Questa azione colpisce tutti gli altri giocatori.",
  howToPlayActionDiscardTitle: "Icona carte",
  howToPlayActionDiscardDesc: "Questa azione serve a recuperare un ingrediente dagli scarti.",
  howToPlayActionNegationTitle: "Icona X",
  howToPlayActionNegationDesc: "Questa è la carta Negazione.",
  howToPlayOthersDiscardLabel: "Gli altri scartano:",
  howToPlayEffectLabel: "Effetto:",
  howToPlayEffectTenedor: "Rubi 1 ingrediente dal tavolo di un giocatore.",
  howToPlayEffectLadron: "Rubi il cappello principale di un giocatore.",
  howToPlayEffectIntercambioSombreros: "Scambi i cappelli con un giocatore.",
  howToPlayEffectIntercambioMesa: "Scambi il tuo tavolo ingredienti con quello di un giocatore.",
  howToPlayEffectGloton: "Svuoti il tavolo ingredienti di un giocatore.",
  howToPlayGoalTitle: "Obiettivo del gioco",
  howToPlayEffectPercheroCubierto: "Blocca l'armadio di un altro giocatore durante il suo turno successivo, a meno che scarti 2 carte quando la riceve.",
  howToPlayGoalDesc: "Vince chi completa per primo tutti i burger obiettivo.",
  howToPlayMainHatsTitle: "Cappelli principali",
  howToPlayMainHatsDesc: "I tuoi cappelli principali determinano quali carte ingrediente puoi giocare nel tuo turno.",
  howToPlayHatButtonsTitle: "Pulsanti del cappello principale",
  howToPlayChangeHatRule: "Cambia: usalo prima di giocare; dopo potrai giocare solo 1 ingrediente.",
  howToPlayAddHatRule: "Aggiungi: usalo prima di giocare; dopo potrai giocare solo 1 ingrediente.",
  howToPlayClosetTitle: "Appendiabiti",
  howToPlayClosetDesc: (n) => `Qui conservi cappelli extra per cambiare o aggiungere. Al momento ne hai ${n}.`,
  prevPage: "Precedente",
  nextPage: "Successiva",
  howToPlayActionPageSingle: "Azioni: un giocatore",
  howToPlayActionPageGlobal: "Azioni: tutti gli altri giocatori",
  howToPlayActionPageNegDiscard: "Azioni: negazione e scarto",
  tiPlayIngDesc: "Gioca una carta ingrediente che corrisponda al tuo cappello principale e di cui il tuo burger abbia bisogno.",
  tiPlayCardDesc: "Gioca una carta azione (⚡) per colpire gli avversari. Possono bloccarla con Negazione 🚫!",
  tiDiscardDesc: "Scarta qualsiasi carta dalla tua mano per finire il turno. La mano si riempie automaticamente.",
  extraPlayLabel: "🍔 Puoi aggiungere un ingrediente",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Stanza",
  log: "📋 Log",
  chat: "💬 Chat",
  leave: "🚪 Esci",
  opponents: "AVVERSARI",
  historyLog: "CRONOLOGIA",
  noEvents: "Nessun evento",
  burgers: "HAMBURGER",
  table: "TAVOLO",
  tableCount: (n) => `TAVOLO (${n} ingredienti)`,
  emptyTable: "Tavolo vuoto",
  sharedGoalsLabel: "Obiettivi condivisi",
  mainHat: "PRINCIPALE",
  closet: "ARMADIO",
  viewCloset: (n) => `🧥 Vedi armadio (${n})`,
  changeHat: "🎩 Cambia",
  changeHatTooltip: "Cambia il tuo cappello principale (costa metà della mano)",
  addHat: "➕ Aggiungi",
  addHatTooltip: "Aggiungi un cappello (scarta tutta la mano, max ridotto)",
  hand: "MANO",
  maxReduced: "Max ridotto per aggiunta",
  canPlay: "✅ Giocabile",
  cantPlay: "❌ Non giocabile",
  cantPlayNow: "❌ Non puoi giocare questa carta ora",
  canPlayThis: "✅ Puoi giocare questa carta",
  play: "▶ Gioca",
  discard: "🗑 Scarta",
  skipTurn: "⏭ Passa turno",
  waitingOnline: (name) => `🌐 In attesa della mossa di ${name}...`,
  waitingLocal: (name) => `⏳ In attesa di ${name}...`,
  cardsInHand: (n) => `🃏 ${n} carte in mano`,
  turn: "⟵ turno",
  wildcardChoose: "Scegli l'ingrediente di cui hai bisogno",
  ingredientCard: "🃏 Carta Ingrediente",
  ingredientTag: "Ingrediente",
  actionCard: "⚡ Carta Azione",
  tableTab: "🍔 Tavolo",
  rivalsTab: "👥 Rivali",
  chatTab: "💬 Chat",
  chooseOpponent: "Scegli avversario",
  tableLabel: "Tavolo",
  empty: "vuoto",
  burgersLabel: "Hamburger",
  cancel: "Annulla",
  forkSteal: "🍴 La Forchetta — Scegli ingrediente da rubare",
  chooseNewHat: "🎩 Scegli nuovo cappello principale",
  waitingHatChoice: (name) => `⏳ In attesa che ${name} scelga il suo cappello...`,
  hatStolen: "Il tuo cappello principale è stato rubato. Scegline uno dall'armadio.",
  hatExchange: "🔄 Scambio di Cappelli",
  hatExchangeDesc: (name) => `Scegli il cappello da dare e quello da ricevere da ${name}.`,
  yourHatToGive: "Il tuo cappello da dare:",
  hatToReceive: (name) => `Cappello che vuoi da ${name}:`,
  exchange: "Scambia",
  close: "Chiudi",
  changeHatStep1: "🎩 Cambia Cappello — passo 1: scegli cappello",
  changeHatStep1Desc: (n) => `Scegli un cappello dall'armadio. Poi sceglierai ${n} cart${n !== 1 ? 'e' : 'a'} da scartare.`,
  changeHatStep2: (lang) => `🎩 Cambia a ${lang} — passo 2: scegli carte`,
  moreCards: (n) => `${n} cart${n !== 1 ? 'e' : 'a'} in più`,
  ready: "Pronto!",
  goBack: "← Indietro",
  confirmDiscard: "Conferma scarto",
  addHatModal: "➕ Aggiungi Cappello — scarta tutta la mano",
  addHatDesc: (max) => `Scegli un cappello dall'armadio. Scarti tutta la mano e il max di carte si riduce di 1 (a ${max}).`,
  trashBin: "🗑️ Il Cestino — Scegli una carta dallo scarto",
  trashBinDesc: "Recupera un ingrediente dalla pila degli scarti.",
  wildcard: "🌭 Jolly — Scegli ingrediente",
  wildcardNeeded: "Questi sono gli ingredienti che ti mancano:",
  wildcardAny: "Scegli l'ingrediente che rappresenta il jolly:",
  wildcardActingAs: (name) => `Jolly come: ${name}`,
  wildcardCanBe: "Può rappresentare qualsiasi ingrediente",
  names: "Nomi",
  affectingCards: "Carte che lo influenzano",
  negation: "🚫 Negazione?",
  negationPlayed: (player, card) => `<strong>${player}</strong> ha giocato <strong>${card}</strong>`,
  negationQuestion: "Vuoi usare una carta Negazione per annullare questa azione?",
  deny: "🚫 Nega",
  allow: "✅ Lascia passare",
  noMessages: "Nessun messaggio",
  typeMessage: "Scrivi un messaggio...",
  send: "Invia",
  reconnecting: "Riconnessione alla stanza...",
  leftRoom: "Hai lasciato la stanza",
  roomLabel: "Stanza",
  wantToReturn: "Vuoi tornare nella stanza?",
  returnToRoom: "Torna alla stanza",
  noGoLobby: "No, vai al lobby",
  gamePaused: "Partita in pausa",
  aloneTitle: "Sei solo nella stanza",
  aloneDesc: "Tutti gli altri giocatori se ne sono andati",
  backToLobby: "Torna al lobby",
  espanol: "Spagnolo",
  ingles: "Inglese",
  frances: "Francese",
  italiano: "Italiano",
  aleman: "Tedesco",
  portugues: "Portoghese",
  langLabel: "Lingua",
  friends: "Amici",
  friendsList: "Lista amici",
  friendRequests: "Richieste",
  addFriend: "Aggiungi amico",
  searchUsers: "Cerca utente...",
  sendRequest: "Invia richiesta",
  requestSent: "Richiesta inviata",
  noFriends: "Nessun amico ancora",
  onlineStatus: "Online",
  offlineStatus: "Offline",
  accept: "Accetta",
  decline: "Rifiuta",
  removeFriend: "Rimuovi",
  inviteFriend: "Invita amico",
  inviteSent: "Invito inviato",
  roomInvite: "ti ha invitato in una stanza",
  joinRoom: "Unisciti",
  noRequests: "Nessuna richiesta in sospeso",
  noResults: "Nessun risultato",
  alreadyFriends: "Già amici",
  requestAlreadySent: "Richiesta già inviata",
  autoAccepted: "Accettato automaticamente",
  blockUser: "Blocca",
  unblockUser: "Sblocca",
  blockedUsers: "Bloccati",
  noBlocked: "Nessun utente bloccato",
  inviteToRoom: "Invita nella stanza",
  friendAccepted: "ha accettato la tua richiesta",
  friendRemovedNotif: "non è più tuo amico",
  friendRequestNotif: "ti ha inviato una richiesta di amicizia",
  viewRequest: "Vedi",
  addFriendShort: "Aggiungi",
  profileMenu: "Profilo",
  leaveLocal: "Esci dalla partita",
  leaveLocalConfirm: "Uscire dalla partita contro l’IA e tornare al setup?",
  homeMenu: "Home",
  gameLanguageMenu: "Lingua di gioco"
};

export default it;
