const pt = {
  appTitle: "HUNGRY POLY",
  tagline: "Aprenda vocabulário montando hambúrgueres",
  login: "Entrar",
  register: "Registrar",
  username: "Usuário",
  password: "Senha",
  displayName: "Nome de exibição",
  loading: "Carregando...",
  enter: "Entrar",
  createAccount: "Criar conta",
  playAsGuest: "Jogar como convidado",
  vsAiModePickerTitle: "Escolhe a tua partida contra a IA",
  vsAiModePickerDesc: "Podes comecar uma partida normal ou aprender primeiro com o tutorial.",
  vsAiModePickerNormalLabel: "Partida simples",
  vsAiModePickerNormalNeedHat: "Configura o modo e escolhe o teu chapeu para poderes jogar.",
  vsAiModePickerNormalReady: "Enfrenta as IAs neste modo.",
  vsAiModePickerTutorialLabel: "Tutorial",
  vsAiModePickerTutorialDesc: "Aprende aqui as bases do jogo.",
  yourName: "SEU NOME",
  enterName: "Digite seu nome...",
  chooseLanguage: "ESCOLHA SEU IDIOMA",
  gameMode: "MODO DE JOGO",
  modeClon: "Clone",
  modeEscalera: "Escada",
  modeCaotico: "Caótico",
  modeClonDesc: "Todas iguais",
  modeEscaleraDesc: "Ascendente",
  modeCaoticoDesc: "Tudo aleatório!",
  burgerCount: "HAMBÚRGUERES",
  ingredientCount: "INGREDIENTES POR BURGER",
  cloneIngredientPool: "POOL DE INGREDIENTES",
  cloneIngredientPoolHint: "Escolha quais ingredientes podem aparecer nos hambúrgueres do modo Clone.",
  cloneIngredientPoolLocked: "Pão está sempre incluído.",
  cloneRemovedActions: "CARTAS DE AÇÃO REMOVIDAS",
  cloneRemovedActionsNone: "Esta seleção não remove nenhuma carta de ação.",
  cloneWildcardsToggle: "CURINGAS NO BARALHO",
  cloneWildcardsOn: "Curingas ativados",
  cloneWildcardsOff: "Curingas desativados",
  ingredientsLabelShort: "INGREDIENTES",
  cloneRemovedActionsLabel: "Cartas de ação removidas",
  cloneNoRemovedActions: "Nenhuma carta de ação é removida",
  perPlayerLabel: "POR JOGADOR",
  aiOpponents: "OPONENTES IA",
  addAiPlayer: "Adicionar IA",
  removeAiPlayer: "Remover IA",
  aiDifficulty: "DIFICULDADE IA",
  aiEasy: "Fácil",
  aiMedium: "Médio",
  aiHard: "Difícil",
  aiImpossible: "Impossível",
  opponent1: "1 oponente",
  opponents3: "3 oponentes",
  vsAI: "🎮 vs IA",
  online: "🌐 Online",
  history: "Histórico",
  logout: "Sair",
  back: "← Voltar",
  gameHistory: "Histórico de Partidas",
  games: "PARTIDAS",
  wins: "VITÓRIAS",
  losses: "DERROTAS",
  winrate: "WINRATE",
  all: "Todas",
  winsFilter: "Vitórias",
  lossesFilter: "Derrotas",
  noGames: "Nenhuma partida registrada",
  victory: "Vitória",
  defeatBy: (name) => `Derrota — ${name} venceu`,
  multiplayerOnline: "Multiplayer Online",
  playWithFriends: "Jogue com amigos em tempo real",
  createRoom: "➕ Criar sala",
  lobby: "🏠 Lobby",
  code: "🔑 Código",
  roomType: "TIPO DE SALA",
  private: "🔒 Privada",
  codeOnly: "Somente com código",
  public: "🌐 Pública",
  visibleInLobby: "Visível no lobby",
  roomName: "NOME DA SALA",
  roomNamePlaceholder: "Ex: Partida rápida",
  creating: "⏳ Criando...",
  createRoomBtn: "🎮 Criar sala",
  publicRooms: "SALAS PÚBLICAS",
  loadingRooms: "⏳ Carregando salas...",
  noPublicRooms: "Não há salas ativas",
  filterByMode: "Filtrar por modo",
  noPublicRoomsForMode: "Nenhuma sala pública para esse modo",
  createYourRoom: "Crie sua sala",
  players: "jogadores",
  join: "Entrar",
  roomCode: "CÓDIGO DA SALA",
  roomCodePlaceholder: "Ex: ABCD1",
  joining: "⏳ Entrando...",
  joinBtn: "🔗 Entrar",
  timeout: "Tempo esgotado. Tente novamente.",
  enterNameFirst: "Digite seu nome primeiro",
  backToMenu: "← Voltar ao menu",
  publicRoom: "🌐 SALA PÚBLICA",
  privateRoom: "🔒 CÓDIGO DA SALA",
  codeLabel: "Código",
  shareCode: "Compartilhe este código ou link com seus amigos",
  linkCopied: "✅ Link copiado!",
  inviteLink: "🔗 Convidar com link",
  playersCount: (n) => `JOGADORES (${n}/6)`,
  you: "(você)",
  host: "👑 Host",
  waitingPlayers: "⏳ Aguardando mais jogadores...",
  yourLanguage: "SEU IDIOMA",
  chooseOne: "(escolha um)",
  waitingHats: (n, total) => `⏳ Aguardando chapéus (${n}/${total})`,
  startGame: "🚀 Iniciar partida!",
  chooseHat: "👆 Escolha seu chapéu de idioma",
  waitingHost: "⏳ Aguardando o host iniciar...",
  leaveRoom: "← Sair da sala",
  extraPlayMsg: "Você pode jogar um ingrediente!",
  yourTurn: "Sua vez",
  turnOfPlayer: (name) => `Turno de ${name}`,
  tapContinue: "Toque para continuar...",
  playerWon: (name) => `${name} venceu!`,
  wonByAbandon: "Venceste por abandono!",
  abandonSubtitle: (name) => `${name} saiu da partida.`,
  youLost: "Você perdeu!",
  completedBurgers: "Completou todos os hambúrgueres primeiro",
  playAgain: "🔄 Jogar novamente",
  historyBtn: "📊 Histórico",
  yourTurnLabel: "🎴 Sua vez",
  turnActionsLabel: "O que posso fazer?",
  actionName_milanesa: "A Milanesa",
  actionDesc_milanesa: "Todos descartam pão e ovo",
  actionName_ensalada: "A Salada",
  actionDesc_ensalada: "Todos descartam frutas/verduras",
  actionName_pizza: "A Pizza",
  actionDesc_pizza: "Todos descartam queijo",
  actionName_parrilla: "A Parrilla",
  actionDesc_parrilla: "Todos descartam frango e carne",
  actionName_tenedor: "O Garfo",
  actionDesc_tenedor: "Rouba ingrediente de outro jogador",
  actionName_ladron: "Ladrão de Chapéus",
  actionDesc_ladron: "Rouba chapéu principal",
  actionName_intercambio_sombreros: "Troca de Chapéus",
  actionDesc_intercambio_sombreros: "Troca chapéus",
  actionName_intercambio_hamburguesa: "Troca de Mesa",
  actionDesc_intercambio_hamburguesa: "Troca ingredientes da mesa",
  actionName_perchero_cubierto: "Armário Coberto",
  actionDesc_perchero_cubierto: "Bloqueia trocar/adicionar e cartas de chapéu por um turno",
  actionName_basurero: "A Lixeira",
  actionDesc_basurero: "Recupera do descarte",
  actionName_gloton: "O Guloso",
  actionDesc_gloton: "Esvazia a mesa de outro jogador",
  actionName_negacion: "Negação",
  actionDesc_negacion: "Bloqueia ação inimiga",
  actionName_comecomodines: "Come Coringas",
  actionDesc_comecomodines: "Todos descartam seus coringas da mesa",
  actionNoObjectives: "Nenhum objetivo encontrado para esta carta",
  howToPlayDesc: "Guia rápido do turno: use cartas de ingredientes para completar seu hambúrguer e cartas de ação para afetar a partida.",
  howToPlayPage: "Página",
  howToPlayTurnRulesTitle: "Regras do turno",
  howToPlayModeIntro: "Cada partida usa um modo diferente. Aqui você pode ver qual está ativo agora e o que muda no objetivo.",
  currentModeBadge: "Atual",
  modeClonDetailed: "Todos os jogadores recebem exatamente os mesmos hambúrgueres objetivo. A dificuldade está em completá-los antes dos outros, não em ter pedidos diferentes.",
  modeEscaleraDetailed: "Seus hambúrgueres crescem do mais simples ao mais complexo. Você começa com objetivos fáceis e cada hambúrguer seguinte pede mais ingredientes.",
  modeCaoticoDetailed: "A quantidade de hambúrgueres e os ingredientes necessários mudam de forma mais imprevisível. É o modo mais variável e pode gerar partidas curtas ou bem exigentes.",
  howToPlayRuleOneCard: "Por turno você só pode jogar uma carta: de ingrediente ou de ação.",
  howToPlayRuleHatButtonsBeforePlay: "Os botões Trocar e Adicionar só podem ser usados antes de jogar uma carta.",
  howToPlayRuleHatButtonsIngredientOnly: "Se usar Trocar ou Adicionar, depois só poderá jogar uma carta de ingrediente.",
  howToPlayIngredientTitle: "Carta de Ingrediente",
  howToPlayIngredientDesc: "A carta de ingrediente deve combinar com seu chapéu principal e ser um ingrediente que seu hambúrguer ainda precisa.",
  howToPlayActionTitle: "Carta de Ação",
  howToPlayActionDesc: "As cartas de ação permitem roubar, trocar ou bloquear jogadas de acordo com o ícone de cada carta.",
  howToPlayActionSingleTitle: "Ícone de uma pessoa",
  howToPlayActionSingleDesc: "Esta ação afeta apenas um jogador.",
  howToPlayActionGlobalTitle: "Ícone de várias pessoas",
  howToPlayActionGlobalDesc: "Esta ação afeta todos os outros jogadores.",
  howToPlayActionDiscardTitle: "Ícone de cartas",
  howToPlayActionDiscardDesc: "Esta ação serve para recuperar um ingrediente do descarte.",
  howToPlayActionNegationTitle: "Ícone X",
  howToPlayActionNegationDesc: "Esta é a carta de Negação.",
  howToPlayOthersDiscardLabel: "Os outros descartam:",
  howToPlayEffectLabel: "Efeito:",
  howToPlayEffectTenedor: "Você rouba 1 ingrediente da mesa de um jogador.",
  howToPlayEffectLadron: "Você rouba o chapéu principal de um jogador.",
  howToPlayEffectIntercambioSombreros: "Você troca chapéus com um jogador.",
  howToPlayEffectIntercambioMesa: "Você troca sua mesa de ingredientes com a de um jogador.",
  howToPlayEffectGloton: "Você esvazia a mesa de ingredientes de um jogador.",
  howToPlayGoalTitle: "Objetivo do jogo",
  howToPlayEffectPercheroCubierto: "Bloqueia o armário de outro jogador durante o próximo turno dele, a menos que descarte 2 cartas ao recebê-la.",
  howToPlayGoalDesc: "Vence quem completar primeiro todos os hambúrgueres objetivo.",
  howToPlayMainHatsTitle: "Chapéus principais",
  howToPlayMainHatsDesc: "Seus chapéus principais determinam quais cartas de ingrediente você pode jogar no turno.",
  howToPlayHatButtonsTitle: "Botões do chapéu principal",
  howToPlayChangeHatRule: "Trocar: use antes de jogar carta; depois só poderá jogar 1 ingrediente.",
  howToPlayAddHatRule: "Adicionar: use antes de jogar carta; depois só poderá jogar 1 ingrediente.",
  howToPlayClosetTitle: "Cabideiro",
  howToPlayClosetDesc: (n) => `Aqui você guarda chapéus extras para trocar ou adicionar. Atualmente você tem ${n}.`,
  prevPage: "Anterior",
  nextPage: "Próxima",
  howToPlayActionPageSingle: "Ações: um jogador",
  howToPlayActionPageGlobal: "Ações: todos os outros jogadores",
  howToPlayActionPageNegDiscard: "Ações: negação e descarte",
  tiPlayIngDesc: "Jogue uma carta de ingrediente que corresponda ao seu chapéu principal e que seu hambúrguer precise.",
  tiPlayCardDesc: "Jogue uma carta de ação (⚡) para afetar adversários. Eles podem bloqueá-la com Negação 🚫!",
  tiDiscardDesc: "Descarte qualquer carta da sua mão para terminar seu turno. Sua mão é reabastecida automaticamente.",
  extraPlayLabel: "🍔 Você pode adicionar um ingrediente",
  waitingPlayer: (name) => `⏳ ${name}`,
  room: "Sala",
  log: "📋 Log",
  chat: "💬 Chat",
  leave: "🚪 Sair",
  opponents: "OPONENTES",
  historyLog: "HISTÓRICO",
  noEvents: "Sem eventos ainda",
  burgers: "HAMBÚRGUERES",
  table: "MESA",
  tableCount: (n) => `MESA (${n} ingredientes)`,
  emptyTable: "Mesa vazia",
  sharedGoalsLabel: "Objetivos compartilhados",
  mainHat: "PRINCIPAL",
  closet: "ARMÁRIO",
  viewCloset: (n) => `🧥 Ver armário (${n})`,
  changeHat: "🎩 Trocar",
  changeHatTooltip: "Troque seu chapéu principal (custa metade da mão)",
  addHat: "➕ Adicionar",
  addHatTooltip: "Adicione um chapéu extra (descarta toda a mão, máx reduzido)",
  hand: "MÃO",
  maxReduced: "Máx reduzido por adição",
  canPlay: "✅ Pode jogar",
  cantPlay: "❌ Não pode jogar",
  cantPlayNow: "❌ Não pode jogar esta carta agora",
  canPlayThis: "✅ Você pode jogar esta carta",
  play: "▶ Jogar",
  discard: "🗑 Descartar",
  skipTurn: "⏭ Passar vez",
  waitingOnline: (name) => `🌐 Aguardando jogada de ${name}...`,
  waitingLocal: (name) => `⏳ Aguardando ${name}...`,
  cardsInHand: (n) => `🃏 ${n} cartas na mão`,
  turn: "⟵ vez",
  wildcardChoose: "Escolha o ingrediente que você precisa",
  ingredientCard: "🃏 Carta de Ingrediente",
  ingredientTag: "Ingrediente",
  actionCard: "⚡ Carta de Ação",
  tableTab: "🍔 Mesa",
  rivalsTab: "👥 Rivais",
  chatTab: "💬 Chat",
  chooseOpponent: "Escolha oponente",
  tableLabel: "Mesa",
  empty: "vazia",
  burgersLabel: "Hambúrgueres",
  cancel: "Cancelar",
  forkSteal: "🍴 O Garfo — Escolha ingrediente para roubar",
  chooseNewHat: "🎩 Escolha novo chapéu principal",
  waitingHatChoice: (name) => `⏳ Aguardando ${name} escolher seu chapéu...`,
  hatStolen: "Seu chapéu principal foi roubado. Escolha um do armário.",
  hatExchange: "🔄 Troca de Chapéus",
  hatExchangeDesc: (name) => `Escolha o chapéu para dar e o que quer receber de ${name}.`,
  yourHatToGive: "Seu chapéu para dar:",
  hatToReceive: (name) => `Chapéu que quer de ${name}:`,
  exchange: "Trocar",
  close: "Fechar",
  changeHatStep1: "🎩 Trocar Chapéu — passo 1: escolher chapéu",
  changeHatStep1Desc: (n) => `Escolha um chapéu do armário. Depois escolherá ${n} carta${n !== 1 ? 's' : ''} para descartar.`,
  changeHatStep2: (lang) => `🎩 Trocar para ${lang} — passo 2: escolher cartas`,
  moreCards: (n) => `mais ${n} carta${n !== 1 ? 's' : ''}`,
  ready: "Pronto!",
  goBack: "← Voltar",
  confirmDiscard: "Confirmar descarte",
  addHatModal: "➕ Adicionar Chapéu — descarta toda a mão",
  addHatDesc: (max) => `Escolha um chapéu do armário. Você descarta toda a mão e o máximo de cartas é reduzido em 1 (para ${max}).`,
  trashBin: "🗑️ A Lixeira — Escolha uma carta do descarte",
  trashBinDesc: "Resgate um ingrediente da pilha de descarte.",
  wildcard: "🌭 Coringa — Escolha ingrediente",
  wildcardNeeded: "Estes são os ingredientes que faltam:",
  wildcardAny: "Escolha o ingrediente que o coringa representa:",
  wildcardActingAs: (name) => `Coringa como: ${name}`,
  wildcardCanBe: "Pode representar qualquer ingrediente",
  names: "Nomes",
  affectingCards: "Cartas que o afetam",
  negation: "🚫 Negação?",
  negationPlayed: (player, card) => `<strong>${player}</strong> jogou <strong>${card}</strong>`,
  negationQuestion: "Quer usar uma carta de Negação para cancelar esta ação?",
  deny: "🚫 Negar",
  allow: "✅ Deixar passar",
  noMessages: "Sem mensagens ainda",
  typeMessage: "Escreva uma mensagem...",
  send: "Enviar",
  reconnecting: "Reconectando à sala...",
  leftRoom: "Você saiu da sala",
  roomLabel: "Sala",
  wantToReturn: "Deseja voltar à sala?",
  returnToRoom: "Voltar à sala",
  noGoLobby: "Não, ir ao lobby",
  gamePaused: "Jogo pausado",
  aloneTitle: "Você está sozinho na sala",
  aloneDesc: "Todos os outros jogadores saíram",
  backToLobby: "Voltar ao lobby",
  espanol: "Espanhol",
  ingles: "Inglês",
  frances: "Francês",
  italiano: "Italiano",
  aleman: "Alemão",
  portugues: "Português",
  langLabel: "Idioma",
  friends: "Amigos",
  friendsList: "Lista de amigos",
  friendRequests: "Pedidos",
  addFriend: "Adicionar amigo",
  searchUsers: "Procurar utilizador...",
  sendRequest: "Enviar pedido",
  requestSent: "Pedido enviado",
  noFriends: "Ainda sem amigos",
  onlineStatus: "Online",
  offlineStatus: "Offline",
  accept: "Aceitar",
  decline: "Recusar",
  removeFriend: "Remover",
  inviteFriend: "Convidar amigo",
  inviteSent: "Convite enviado",
  roomInvite: "convidou-te para uma sala",
  joinRoom: "Entrar",
  noRequests: "Sem pedidos pendentes",
  noResults: "Sem resultados",
  alreadyFriends: "Já são amigos",
  requestAlreadySent: "Pedido já enviado",
  autoAccepted: "Aceite automaticamente",
  blockUser: "Bloquear",
  unblockUser: "Desbloquear",
  blockedUsers: "Bloqueados",
  noBlocked: "Sem utilizadores bloqueados",
  inviteToRoom: "Convidar para a sala",
  friendAccepted: "aceitou o teu pedido",
  friendRemovedNotif: "deixou de ser teu amigo",
  friendRequestNotif: "enviou-te um pedido de amizade",
  viewRequest: "Ver",
  addFriendShort: "Adicionar",
  profileMenu: "Perfil",
  leaveLocal: "Sair da partida",
  leaveLocalConfirm: "Sair da partida contra a IA e voltar ao setup?",
  homeMenu: "Inicio",
  gameLanguageMenu: "Idioma do jogo"
};

export default pt;
